// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import {
	className,
	className2,
	className3,
	className4,
	className5,
	className6,
	className7,
	className8,
	className9,
	css,
	css2,
	css3,
	css4,
	css5,
	css6,
	css7,
	css8,
	css9,
	fonts,
	fonts2,
	fonts3,
	fonts4,
	fonts5,
	fonts6,
	fonts7,
	fonts8,
	fonts9,
} from "../chunks/chunk-OK4YEQA6.js";
import { stdin_default } from "../chunks/chunk-ZXU7IT6C.js";
import "../chunks/chunk-ELYQXSRD.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:card/blog-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oBhsXD0CAvknGat7pmg9/lHeKdh9iRdEzsSiZy0js/RK7VFsD5g.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	Floating,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOverlayState,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/dN7S1JvbiRGZUv89yKT4/VFFWyHL0r2LzMDy1NSkA/dKg4d4Wgl.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;DM Sans-500",
	"GF;DM Sans-700",
	"GF;DM Sans-700italic",
	"GF;DM Sans-500italic",
]);
var fonts10 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
				weight: "500",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwARZthS2f3ZGMZpg.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9uCm32RmYJpso5.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat-7DW32RmYJpso5.woff2",
				weight: "500",
			},
		],
	},
];
var css10 = [
	'.framer-SQFDJ .framer-styles-preset-9w7x32:not(.rich-text-wrapper), .framer-SQFDJ .framer-styles-preset-9w7x32.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, #575757); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 1200px) { .framer-SQFDJ .framer-styles-preset-9w7x32:not(.rich-text-wrapper), .framer-SQFDJ .framer-styles-preset-9w7x32.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, #575757); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-SQFDJ .framer-styles-preset-9w7x32:not(.rich-text-wrapper), .framer-SQFDJ .framer-styles-preset-9w7x32.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, #575757); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-SQFDJ .framer-styles-preset-9w7x32:not(.rich-text-wrapper), .framer-SQFDJ .framer-styles-preset-9w7x32.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, #575757); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className10 = "framer-SQFDJ";

// /:https://framerusercontent.com/modules/oBhsXD0CAvknGat7pmg9/lHeKdh9iRdEzsSiZy0js/RK7VFsD5g.js
var SecondaryButtonFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	PTwSr_FG3: {
		hover: true,
	},
};
var cycleOrder = ["PTwSr_FG3", "nE1M_jpLE"];
var serializationHash = "framer-LD84w";
var variantClassNames = {
	nE1M_jpLE: "framer-v-5uxquh",
	PTwSr_FG3: "framer-v-1ka5dzh",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Overlay = ({
	children,
	blockDocumentScrolling,
	dismissWithEsc,
	enabled = true,
}) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
		dismissWithEsc: enabled && dismissWithEsc,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "PTwSr_FG3",
	Phone: "nE1M_jpLE",
};
var getProps = ({
	bigTitle,
	date,
	height,
	id,
	image,
	link,
	overviewForCard,
	visible,
	width,
	...props
}) => {
	return {
		...props,
		cm3JAkpVP: link ?? props.cm3JAkpVP,
		dauw6HJQy: date ?? props.dauw6HJQy ?? "10 July 2024",
		fGbL4VXk0: visible ?? props.fGbL4VXk0 ?? true,
		ik63V3APS: overviewForCard ?? props.ik63V3APS ?? (
			<React.Fragment>
				<motion.p>
					{
						"We're your strategic partner, deeply understanding your brand's essence."
					}
				</motion.p>
			</React.Fragment>
		),
		k91hGGehh:
			bigTitle ??
			props.k91hGGehh ??
			"5 Smartphone Habits That Shape User Behavior in 2024",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "PTwSr_FG3",
		WpcUmlouJ: image ?? props.WpcUmlouJ,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className11,
		layoutId,
		variant,
		dauw6HJQy: dauw6HJQy2,
		WpcUmlouJ: WpcUmlouJ2,
		cm3JAkpVP: cm3JAkpVP2,
		k91hGGehh: k91hGGehh2,
		fGbL4VXk0: fGbL4VXk02,
		ik63V3APS: ik63V3APS2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "PTwSr_FG3",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterujujp2 = ({ overlay }) =>
		activeVariantCallback(async (...args) => {
			setGestureState({
				isHovered: true,
			});
			overlay.show();
		});
	const sharedStyleClassNames = [
		className10,
		className3,
		className9,
		className4,
		className,
		className2,
		className7,
		className8,
		className6,
		className5,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Overlay blockDocumentScrolling={false} dismissWithEsc={false}>
					{(overlay) => (
						<_Fragment>
							<Transition value={transition1}>
								<Link
									href={cm3JAkpVP2}
									motionChild={true}
									nodeId={"PTwSr_FG3"}
									scopeId={"RK7VFsD5g"}
								>
									<motion.a
										{...restProps}
										{...gestureHandlers}
										className={`${cx(scopingClassNames, "framer-1ka5dzh", className11, classNames)} framer-vr0pxk`}
										data-border={true}
										data-framer-name={"Desktop"}
										data-highlight={true}
										id={`${layoutId}-1ka5dzh`}
										layoutDependency={layoutDependency}
										layoutId={"PTwSr_FG3"}
										onMouseEnter={onMouseEnterujujp2({
											overlay,
										})}
										ref={refBinding}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgb(226, 225, 217)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-89f00802-8f85-4956-81b5-bedca004d6ba, rgb(255, 255, 255))",
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
											...style,
										}}
										variants={{
											"PTwSr_FG3-hover": {
												backgroundColor: "rgb(247, 247, 247)",
											},
										}}
										{...addPropertyOverrides(
											{
												"PTwSr_FG3-hover": {
													"data-framer-name": void 0,
												},
												nE1M_jpLE: {
													"data-framer-name": "Phone",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion.div
											className={"framer-1k6u3lb"}
											data-framer-name={"Image"}
											layoutDependency={layoutDependency}
											layoutId={"EjMnsXXEV"}
											style={{
												borderBottomLeftRadius: 0,
												borderBottomRightRadius: 0,
												borderTopLeftRadius: 0,
												borderTopRightRadius: 0,
											}}
											variants={{
												"PTwSr_FG3-hover": {
													borderBottomLeftRadius: 8,
													borderBottomRightRadius: 8,
													borderTopLeftRadius: 8,
													borderTopRightRadius: 8,
												},
											}}
										>
											<Image
												background={{
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 20 + 0 + 0,
													),
													sizes: `max(${componentViewport?.width || "100vw"} - 40px, 1px)`,
													...toResponsiveImage(WpcUmlouJ2),
												}}
												className={"framer-fgjh9d"}
												data-framer-name={"Image"}
												layoutDependency={layoutDependency}
												layoutId={"SXseVW6kv"}
												style={{
													borderBottomLeftRadius: 8,
													borderBottomRightRadius: 8,
													borderTopLeftRadius: 8,
													borderTopRightRadius: 8,
													scale: 1,
												}}
												variants={{
													"PTwSr_FG3-hover": {
														scale: 1.01,
													},
												}}
											/>
										</motion.div>
										<motion.div
											className={"framer-1lx18jc"}
											data-framer-name={"Text Content with Date"}
											layoutDependency={layoutDependency}
											layoutId={"gS4EogRqz"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1h2ssof"}
												data-framer-name={"10 July 2024"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"SYk9QjkXz"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-8357580f-5ed3-47c0-804c-d27da27cc3fb, rgb(153, 153, 153))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={dauw6HJQy2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-9w7x32"}
														data-styles-preset={"dKg4d4Wgl"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-8357580f-5ed3-47c0-804c-d27da27cc3fb, rgb(153, 153, 153)))",
														}}
													>
														{"10 July 2024"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<motion.div
												className={"framer-19gzxiq"}
												data-framer-name={"Text Content with Button"}
												layoutDependency={layoutDependency}
												layoutId={"UtHRtoG5n"}
											>
												<motion.div
													className={"framer-12e791a"}
													data-framer-name={"Title + Paragraph"}
													layoutDependency={layoutDependency}
													layoutId={"l1U92Lir_"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1wdi0c0"}
														data-framer-name={
															"5 Smartphone Habits That Shape User Behavior in 2024"
														}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"Y0fj3mByp"}
														style={{
															"--extracted-1w1cjl5":
																"var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23))",
															"--framer-paragraph-spacing": "0px",
														}}
														text={k91hGGehh2}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h6
																className={"framer-styles-preset-1am8ijr"}
																data-styles-preset={"htXtgXqYm"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-1w1cjl5, var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23)))",
																}}
															>
																{
																	"5 Smartphone Habits That Shape User Behavior in 2024"
																}
															</motion.h6>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-gb7hrj"}
														data-framer-name={
															"We're your strategic partner, deeply understanding your brand's essence."
														}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"rTanifUYy"}
														style={{
															"--framer-paragraph-spacing": "0px",
														}}
														stylesPresetsClassNames={{
															a: "framer-styles-preset-tgx3ii",
															blockquote: "framer-styles-preset-txrbfq",
															code: "framer-styles-preset-13hde2x",
															h2: "framer-styles-preset-u68kn0",
															h3: "framer-styles-preset-axnkz1",
															h4: "framer-styles-preset-1xx5m9h",
															h5: "framer-styles-preset-9w35rd",
															h6: "framer-styles-preset-1am8ijr",
															p: "framer-styles-preset-yv4o5b",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														{ik63V3APS2}
													</RichText>
												</motion.div>
												{fGbL4VXk02 && (
													<ComponentViewportProvider
														height={48}
														width={`calc(${componentViewport?.width || "100vw"} - 40px)`}
														y={
															(componentViewport?.y || 0) +
															20 +
															270 +
															0 +
															120 +
															0 +
															(0 +
																122.4 +
																((Math.max(
																	0,
																	(Math.max(
																		0,
																		((componentViewport?.height || 520) -
																			40 -
																			270) /
																			1,
																	) *
																		1 -
																		0 -
																		120) /
																		1,
																) *
																	1 -
																	0 -
																	122.4) /
																	1) *
																	1)
														}
														{...addPropertyOverrides(
															{
																nE1M_jpLE: {
																	y:
																		(componentViewport?.y || 0) +
																		20 +
																		270 +
																		0 +
																		120 +
																		0 +
																		170.4,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-1jskfh9-container"}
															layoutDependency={layoutDependency}
															layoutId={"r86N2GU7s-container"}
															nodeId={"r86N2GU7s"}
															rendersWithMotion={true}
															scopeId={"RK7VFsD5g"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																id: "r86N2GU7s",
																layoutId: "r86N2GU7s",
																pRhNYXVlp: "Read Full Story",
																style: {
																	width: "100%",
																},
																variant: "SwrUmNEKc",
																width: "100%",
																...addPropertyOverrides(
																	{
																		nE1M_jpLE: {
																			variant: "Qfzvhz0oX",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</motion.div>
										</motion.div>
										<AnimatePresence>
											{overlay.visible && (
												<Floating
													alignment={"center"}
													anchorRef={refBinding}
													className={cx(scopingClassNames, classNames)}
													collisionDetection={true}
													collisionDetectionPadding={20}
													data-framer-portal-id={`${layoutId}-1ka5dzh`}
													offsetX={0}
													offsetY={10}
													onDismiss={overlay.hide}
													placement={"bottom"}
													safeArea={true}
													zIndex={11}
												>
													<MotionDivWithFX
														__perspectiveFX={false}
														__smartComponentFX={true}
														__targetOpacity={1}
														animate={animation1}
														className={"framer-1ltrvx5"}
														exit={animation}
														initial={animation2}
														layoutDependency={layoutDependency}
														layoutId={"iXBH8nXEc"}
														ref={ref1}
														role={"dialog"}
														style={{
															backgroundColor: "rgb(255, 255, 255)",
															borderBottomLeftRadius: 10,
															borderBottomRightRadius: 10,
															borderTopLeftRadius: 10,
															borderTopRightRadius: 10,
															boxShadow:
																"0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
														}}
													/>
												</Floating>
											)}
										</AnimatePresence>
									</motion.a>
								</Link>
							</Transition>
						</_Fragment>
					)}
				</Overlay>
			</Variants>
		</LayoutGroup>
	);
});
var css11 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-LD84w.framer-vr0pxk, .framer-LD84w .framer-vr0pxk { display: block; }",
	".framer-LD84w.framer-1ka5dzh { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: 520px; justify-content: flex-start; overflow: visible; padding: 20px; position: relative; text-decoration: none; width: 370px; }",
	".framer-LD84w .framer-1k6u3lb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-LD84w .framer-fgjh9d { aspect-ratio: 1.32 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 250px); overflow: visible; position: relative; width: 1px; }",
	".framer-LD84w .framer-1lx18jc { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 1px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-LD84w .framer-1h2ssof, .framer-LD84w .framer-1wdi0c0, .framer-LD84w .framer-gb7hrj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-LD84w .framer-19gzxiq { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-LD84w .framer-12e791a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-LD84w .framer-1jskfh9-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-LD84w .framer-1ltrvx5 { height: 150px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-LD84w.framer-v-5uxquh.framer-1ka5dzh { cursor: unset; height: min-content; }",
	".framer-LD84w.framer-v-5uxquh .framer-1lx18jc { flex: none; height: min-content; }",
	".framer-LD84w.framer-v-5uxquh .framer-19gzxiq { flex: none; gap: 16px; height: min-content; justify-content: center; }",
	".framer-LD84w.framer-v-1ka5dzh.hover .framer-1k6u3lb { will-change: var(--framer-will-change-override, transform); }",
	...css10,
	...css3,
	...css9,
	...css4,
	...css,
	...css2,
	...css7,
	...css8,
	...css6,
	...css5,
	'.framer-LD84w[data-border="true"]::after, .framer-LD84w [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerRK7VFsD5g = withCSS(Component, css11, "framer-LD84w");
var stdin_default2 = FramerRK7VFsD5g;
FramerRK7VFsD5g.displayName = "Card/Blog Card";
FramerRK7VFsD5g.defaultProps = {
	height: 520,
	width: 370,
};
addPropertyControls(FramerRK7VFsD5g, {
	variant: {
		options: ["PTwSr_FG3", "nE1M_jpLE"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	dauw6HJQy: {
		defaultValue: "10 July 2024",
		displayTextArea: false,
		title: "Date",
		type: ControlType.String,
	},
	WpcUmlouJ: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	cm3JAkpVP: {
		title: "Link",
		type: ControlType.Link,
	},
	k91hGGehh: {
		defaultValue: "5 Smartphone Habits That Shape User Behavior in 2024",
		displayTextArea: false,
		title: "Big Title",
		type: ControlType.String,
	},
	fGbL4VXk0: {
		defaultValue: true,
		title: "Visible",
		type: ControlType.Boolean,
	},
	ik63V3APS: {
		defaultValue:
			"<p>We're your strategic partner, deeply understanding your brand's essence.</p>",
		title: "Overview for Card",
		type: ControlType.RichText,
	},
});
addFonts(
	FramerRK7VFsD5g,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SecondaryButtonFonts,
		...getFontsFromSharedStyle(fonts10),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts9),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card/blog-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "nE1M_jpLE",
	xl: "PTwSr_FG3",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var blog_card_default = ComponentWithRoot;
export { blog_card_default as default };
