// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import {
	className,
	className2,
	className3,
	className4,
	className5,
	className6,
	className7,
	className8,
	className9,
	css,
	css2,
	css3,
	css4,
	css5,
	css6,
	css7,
	css8,
	css9,
	fonts,
	fonts2,
	fonts3,
	fonts4,
	fonts5,
	fonts6,
	fonts7,
	fonts8,
	fonts9,
} from "../chunks/chunk-OK4YEQA6.js";
import { stdin_default } from "../chunks/chunk-ZXU7IT6C.js";
import "../chunks/chunk-ELYQXSRD.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:card/projects-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cfECFNfM2VbKNEXuJT1q/kElgId9HIrYm9OF9Ryvd/mpanVhdiq.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SecondaryButtonFonts = getFonts(stdin_default);
var enabledGestures = {
	cAWijP5pQ: {
		hover: true,
	},
	l94PrvSLL: {
		hover: true,
	},
};
var cycleOrder = ["cAWijP5pQ", "l94PrvSLL", "dRbpGgJv7"];
var serializationHash = "framer-oRaZV";
var variantClassNames = {
	cAWijP5pQ: "framer-v-yk783m",
	dRbpGgJv7: "framer-v-c2msln",
	l94PrvSLL: "framer-v-36cnt6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Small Desktop": "l94PrvSLL",
	Left: "cAWijP5pQ",
	Mobile: "dRbpGgJv7",
};
var getProps = ({
	buttonLabel,
	category,
	height,
	id,
	image,
	link,
	overview,
	tag01,
	tag02,
	tag03,
	title,
	visible,
	width,
	...props
}) => {
	return {
		...props,
		B669juXtz: buttonLabel ?? props.B669juXtz ?? "Read Full Story",
		EKOEBmddh:
			title ?? props.EKOEBmddh ?? "LawHub\u2014 Framer Website Development",
		gbuvSsAXX: overview ?? props.gbuvSsAXX ?? (
			<React.Fragment>
				<motion.p>{"text"}</motion.p>
			</React.Fragment>
		),
		nqI_Ii8Xs: image ??
			props.nqI_Ii8Xs ?? {
				pixelHeight: 1552,
				pixelWidth: 1400,
				src: "https://framerusercontent.com/images/azr9sN0PIPjQFEPoVIG1PYRSjhM.png?width=1400&height=1552",
				srcSet:
					"https://framerusercontent.com/images/azr9sN0PIPjQFEPoVIG1PYRSjhM.png?scale-down-to=1024&width=1400&height=1552 923w,https://framerusercontent.com/images/azr9sN0PIPjQFEPoVIG1PYRSjhM.png?width=1400&height=1552 1400w",
			},
		QQyPlXms1: tag03 ?? props.QQyPlXms1 ?? "Framer Development",
		ReFF1lQ_S: tag02 ?? props.ReFF1lQ_S ?? "Competitor Analysis",
		UNqrno02U: visible ?? props.UNqrno02U ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "cAWijP5pQ",
		wt28EYFYm: tag01 ?? props.wt28EYFYm ?? "Reaserch",
		XaUwce3fx: category ?? props.XaUwce3fx ?? "[Fintech]",
		yw8d2neAw: link ?? props.yw8d2neAw,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className10,
		layoutId,
		variant,
		XaUwce3fx: XaUwce3fx2,
		EKOEBmddh: EKOEBmddh2,
		gbuvSsAXX: gbuvSsAXX2,
		wt28EYFYm: wt28EYFYm2,
		ReFF1lQ_S: ReFF1lQ_S2,
		QQyPlXms1: QQyPlXms12,
		UNqrno02U: UNqrno02U2,
		yw8d2neAw: yw8d2neAw2,
		nqI_Ii8Xs: nqI_Ii8Xs2,
		B669juXtz: B669juXtz2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "cAWijP5pQ",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className7,
		className2,
		className9,
		className4,
		className,
		className3,
		className8,
		className6,
		className5,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "l94PrvSLL-hover") return false;
		if (baseVariant === "l94PrvSLL") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={yw8d2neAw2}
						motionChild={true}
						nodeId={"cAWijP5pQ"}
						scopeId={"mpanVhdiq"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-yk783m", className10, classNames)} framer-7bh7i4`}
							data-border={true}
							data-framer-name={"Left"}
							layoutDependency={layoutDependency}
							layoutId={"cAWijP5pQ"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgb(226, 225, 217)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(226, 225, 217, 0.4)",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
								...style,
							}}
							variants={{
								"cAWijP5pQ-hover": {
									backgroundColor: "rgba(226, 225, 217, 0.6)",
								},
								"l94PrvSLL-hover": {
									backgroundColor: "rgba(226, 225, 217, 0.6)",
								},
							}}
							{...addPropertyOverrides(
								{
									"cAWijP5pQ-hover": {
										"data-framer-name": void 0,
									},
									"l94PrvSLL-hover": {
										"data-framer-name": void 0,
									},
									dRbpGgJv7: {
										"data-framer-name": "Mobile",
									},
									l94PrvSLL: {
										"data-framer-name": "Small Desktop",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-aum4ce"}
								data-border={true}
								data-framer-name={"Image Container"}
								layoutDependency={layoutDependency}
								layoutId={"IGSywQyOZ"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-403f5250-c23f-4327-bcf3-4fb3df82b8c0, rgb(226, 225, 217))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 20 + 0,
										),
										sizes: `max((${componentViewport?.width || "100vw"} - 60px) / 2, 1px)`,
										...toResponsiveImage(nqI_Ii8Xs2),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1g2dnpr"}
									data-framer-name={" Image"}
									layoutDependency={layoutDependency}
									layoutId={"yLYqOgqZ8"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
										scale: 1,
									}}
									variants={{
										"cAWijP5pQ-hover": {
											scale: 1.01,
										},
										"l94PrvSLL-hover": {
											scale: 1.01,
										},
									}}
									{...addPropertyOverrides(
										{
											dRbpGgJv7: {
												background: {
													alt: "",
													fit: "fill",
													sizes: `max(${componentViewport?.width || "100vw"} - 24px, 1px)`,
													...toResponsiveImage(nqI_Ii8Xs2),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
											l94PrvSLL: {
												background: {
													alt: "",
													fit: "fill",
													sizes: `max(${componentViewport?.width || "100vw"} - 40px, 1px)`,
													...toResponsiveImage(nqI_Ii8Xs2),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								className={"framer-19je1zg"}
								data-framer-name={"All Content"}
								layoutDependency={layoutDependency}
								layoutId={"INN2VtWQh"}
							>
								<motion.div
									className={"framer-24mzbz"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"s39kjkOhj"}
								>
									<motion.div
										className={"framer-1lafwna"}
										data-framer-name={"Title + Category"}
										layoutDependency={layoutDependency}
										layoutId={"AkyUhc977"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1azzjou"}
											data-framer-name={"[Fintech]"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"c82febQpf"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={XaUwce3fx2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-yv4o5b"}
													data-styles-preset={"S8Dv9x0vl"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87)))",
													}}
												>
													{"[Fintech]"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-en8bxh"}
											data-framer-name={
												"LawHub\u2014 Framer Website Development"
											}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"mJfiiKSJs"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											text={EKOEBmddh2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h4
													className={"framer-styles-preset-9w35rd"}
													data-styles-preset={"ERkOWGumt"}
												>
													{"LawHub\u2014 Framer Website Development"}
												</motion.h4>
											</React.Fragment>
										</RichText>
									</motion.div>
									{isDisplayed() && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1nxxe5z"}
											data-framer-name={
												"We're your strategic partner, deeply understanding your brand's essence with a dedicated product owner for each project,"
											}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"bu52nHCNe"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
												"--framer-paragraph-spacing": "0px",
											}}
											stylesPresetsClassNames={{
												a: "framer-styles-preset-tgx3ii",
												blockquote: "framer-styles-preset-txrbfq",
												code: "framer-styles-preset-13hde2x",
												h1: "framer-styles-preset-o3e5h0",
												h2: "framer-styles-preset-u68kn0",
												h3: "framer-styles-preset-axnkz1",
												h4: "framer-styles-preset-1xx5m9h",
												h5: "framer-styles-preset-9w35rd",
												h6: "framer-styles-preset-1am8ijr",
												p: "framer-styles-preset-yv4o5b",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											{gbuvSsAXX2}
										</RichText>
									)}
									<motion.div
										className={"framer-1j15urj"}
										data-framer-name={"Tags"}
										layoutDependency={layoutDependency}
										layoutId={"fzDAbemZ7"}
									>
										<motion.div
											className={"framer-1wmypat"}
											data-border={true}
											data-framer-name={"01"}
											layoutDependency={layoutDependency}
											layoutId={"cfMOHyv9s"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-fe4b6e9c-0c78-422e-bf1e-634d90c9df05, rgb(205, 203, 203))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												borderBottomLeftRadius: 90,
												borderBottomRightRadius: 90,
												borderTopLeftRadius: 90,
												borderTopRightRadius: 90,
											}}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-23izjs"}
												data-framer-name={"Reaserch"}
												fonts={["GF;DM Sans-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"IdxoQgCbG"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={wt28EYFYm2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
															"--framer-font-family":
																'"DM Sans", "DM Sans Placeholder", sans-serif',
															"--framer-font-size": "12px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.6em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87)))",
														}}
													>
														{"Reaserch"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<motion.div
											className={"framer-6p5qxq"}
											data-border={true}
											data-framer-name={"02"}
											layoutDependency={layoutDependency}
											layoutId={"k5NdF6D47"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-fe4b6e9c-0c78-422e-bf1e-634d90c9df05, rgb(205, 203, 203))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												borderBottomLeftRadius: 90,
												borderBottomRightRadius: 90,
												borderTopLeftRadius: 90,
												borderTopRightRadius: 90,
											}}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-16bcjqa"}
												data-framer-name={"Competitor Analysis"}
												fonts={["GF;DM Sans-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"v1s4_hWrx"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={ReFF1lQ_S2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
															"--framer-font-family":
																'"DM Sans", "DM Sans Placeholder", sans-serif',
															"--framer-font-size": "12px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.6em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87)))",
														}}
													>
														{"Competitor Analysis"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<motion.div
											className={"framer-dic763"}
											data-border={true}
											data-framer-name={"03"}
											layoutDependency={layoutDependency}
											layoutId={"aJzjxSvk7"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-fe4b6e9c-0c78-422e-bf1e-634d90c9df05, rgb(205, 203, 203))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												borderBottomLeftRadius: 90,
												borderBottomRightRadius: 90,
												borderTopLeftRadius: 90,
												borderTopRightRadius: 90,
											}}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-xlfsht"}
												data-framer-name={"Framer Development"}
												fonts={["GF;DM Sans-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"A_1JnPXgN"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={QQyPlXms12}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
															"--framer-font-family":
																'"DM Sans", "DM Sans Placeholder", sans-serif',
															"--framer-font-size": "12px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.6em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87)))",
														}}
													>
														{"Framer Development"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								</motion.div>
								{UNqrno02U2 && (
									<ComponentViewportProvider
										height={48}
										width={`max((${componentViewport?.width || "100vw"} - 60px) / 2, 1px)`}
										{...addPropertyOverrides(
											{
												dRbpGgJv7: {
													width: `calc(${componentViewport?.width || "100vw"} - 24px)`,
												},
												l94PrvSLL: {
													width: `calc(${componentViewport?.width || "100vw"} - 40px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1ucqqbk-container"}
											layoutDependency={layoutDependency}
											layoutId={"mZFg0sHtB-container"}
											nodeId={"mZFg0sHtB"}
											rendersWithMotion={true}
											scopeId={"mpanVhdiq"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "mZFg0sHtB",
												layoutId: "mZFg0sHtB",
												pRhNYXVlp: B669juXtz2,
												style: {
													width: "100%",
												},
												variant: "SwrUmNEKc",
												width: "100%",
												...addPropertyOverrides(
													{
														dRbpGgJv7: {
															variant: "Qfzvhz0oX",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css10 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oRaZV.framer-7bh7i4, .framer-oRaZV .framer-7bh7i4 { display: block; }",
	".framer-oRaZV.framer-yk783m { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px; position: relative; text-decoration: none; width: 760px; }",
	".framer-oRaZV .framer-aum4ce { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-oRaZV .framer-1g2dnpr { flex: 1 0 0px; height: 388px; position: relative; width: 1px; }",
	".framer-oRaZV .framer-19je1zg { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: auto; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-oRaZV .framer-24mzbz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-oRaZV .framer-1lafwna { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-oRaZV .framer-1azzjou, .framer-oRaZV .framer-en8bxh, .framer-oRaZV .framer-1nxxe5z { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-oRaZV .framer-1j15urj { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-oRaZV .framer-1wmypat, .framer-oRaZV .framer-6p5qxq, .framer-oRaZV .framer-dic763 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 4px 8px 4px 8px; position: relative; width: min-content; }",
	".framer-oRaZV .framer-23izjs, .framer-oRaZV .framer-16bcjqa, .framer-oRaZV .framer-xlfsht { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-oRaZV .framer-1ucqqbk-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-oRaZV.framer-v-36cnt6.framer-yk783m { flex-direction: column; }",
	".framer-oRaZV.framer-v-36cnt6 .framer-aum4ce { flex: none; width: 100%; }",
	".framer-oRaZV.framer-v-36cnt6 .framer-19je1zg { align-self: unset; flex: none; height: min-content; width: 100%; }",
	".framer-oRaZV.framer-v-c2msln.framer-yk783m { cursor: unset; flex-direction: column; padding: 12px; width: 300px; }",
	".framer-oRaZV.framer-v-c2msln .framer-aum4ce { flex: none; order: 0; width: 100%; }",
	".framer-oRaZV.framer-v-c2msln .framer-1g2dnpr { aspect-ratio: 0.92 / 1; height: var(--framer-aspect-ratio-supported, 300px); }",
	".framer-oRaZV.framer-v-c2msln .framer-19je1zg { align-self: unset; flex: none; height: min-content; order: 1; width: 100%; }",
	".framer-oRaZV.framer-v-c2msln .framer-24mzbz { gap: 4px; }",
	".framer-oRaZV.framer-v-36cnt6.hover .framer-19je1zg { align-self: unset; }",
	...css7,
	...css2,
	...css9,
	...css4,
	...css,
	...css3,
	...css8,
	...css6,
	...css5,
	'.framer-oRaZV[data-border="true"]::after, .framer-oRaZV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramermpanVhdiq = withCSS(Component, css10, "framer-oRaZV");
var stdin_default2 = FramermpanVhdiq;
FramermpanVhdiq.displayName = "Card/Projects Card";
FramermpanVhdiq.defaultProps = {
	height: 428,
	width: 760,
};
addPropertyControls(FramermpanVhdiq, {
	variant: {
		options: ["cAWijP5pQ", "l94PrvSLL", "dRbpGgJv7"],
		optionTitles: ["Left", "Small Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	XaUwce3fx: {
		defaultValue: "[Fintech]",
		displayTextArea: false,
		title: "Category",
		type: ControlType.String,
	},
	EKOEBmddh: {
		defaultValue: "LawHub\u2014 Framer Website Development",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	gbuvSsAXX: {
		defaultValue: "<p>text</p>",
		title: "Overview",
		type: ControlType.RichText,
	},
	wt28EYFYm: {
		defaultValue: "Reaserch",
		displayTextArea: false,
		title: "Tag 01",
		type: ControlType.String,
	},
	ReFF1lQ_S: {
		defaultValue: "Competitor Analysis",
		displayTextArea: false,
		title: "Tag 02",
		type: ControlType.String,
	},
	QQyPlXms1: {
		defaultValue: "Framer Development",
		displayTextArea: false,
		title: "Tag 03",
		type: ControlType.String,
	},
	UNqrno02U: {
		defaultValue: true,
		title: "Visible",
		type: ControlType.Boolean,
	},
	yw8d2neAw: {
		title: "Link",
		type: ControlType.Link,
	},
	nqI_Ii8Xs: {
		__defaultAssetReference:
			"data:framer/asset-reference,azr9sN0PIPjQFEPoVIG1PYRSjhM.png?originalFilename=Rectangle+29.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	B669juXtz: {
		defaultValue: "Read Full Story",
		displayTextArea: false,
		title: "Button Label",
		type: ControlType.String,
	},
});
addFonts(
	FramermpanVhdiq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "DM Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "DM Sans",
					url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAopxhS2f3ZGMZpg.woff2",
					weight: "400",
				},
			],
		},
		...SecondaryButtonFonts,
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts9),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card/projects-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "dRbpGgJv7",
	xl: "cAWijP5pQ",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var projects_card_default = ComponentWithRoot;
export { projects_card_default as default };
