/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        n8n: {
          canvas: '#1a1d24',
          toolbar: '#22252e',
          node: '#2a2d38',
          panel: '#2a2d38',
          border: '#3d4254',
          'border-hover': '#5a6278',
          text: '#e8eaef',
          muted: '#9ca3af',
          dim: '#6b7280',
          accent: '#ff6d5a',
          port: '#7a8194',
          trigger: '#f59e0b',
          end: '#ef4444',
        },
        canvas: {
          surface: '#1a1d24',
          toolbar: '#22252e',
          node: '#2a2d38',
          panel: '#2a2d38',
          border: '#3d4254',
          'border-hover': '#5a6278',
          text: '#e8eaef',
          muted: '#8b95a8',
          accent: '#4D90D8',
          port: '#6b7289',
          trigger: '#f59e0b',
        },
        workflow: {
          ivory: '#F7F5F1',
          coral: '#EC896F',
          peach: '#FFA27C',
          sand: '#E3B78F',
          blue: '#4D90D8',
          powder: '#C7E3F1',
          text: '#253247',
          secondary: '#667085',
          connector: '#7D8CA3',
          border: 'rgba(125, 140, 163, 0.25)',
          'coral-light': 'rgba(236, 137, 111, 0.12)',
          'peach-light': 'rgba(255, 162, 124, 0.12)',
          'sand-light': 'rgba(227, 183, 143, 0.12)',
          'blue-light': 'rgba(77, 144, 216, 0.12)',
          'powder-light': 'rgba(199, 227, 241, 0.35)',
          muted: '#7D8CA3',
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: '#F7F5F1',
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: 'rgb(223, 252, 161)',
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        black: 'rgb(23, 22, 23)',
        disable: 'rgb(153, 153, 153)',
        white: 'rgb(255, 255, 255)',
        'paragraph-white': 'rgb(87, 87, 87)',
        'paragraph-black': 'rgb(205, 203, 203)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'full': '90px',
      },
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
        display: ['DM Sans', 'system-ui', 'sans-serif'],
        body: ['DM Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    },
    plugins: [require("tailwindcss-animate")],
}
