// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import { className, css, fonts } from "../chunks/chunk-C7IJE73U.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:footer/email
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3OGDE5btaAK3nkoarIxh/0Wdo40DHAbvaCBe1CreJ/Jhd9lh2J6.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	bU2JKRFEH: {
		hover: true,
	},
};
var cycleOrder = ["bU2JKRFEH", "gKiP_vGWQ"];
var serializationHash = "framer-lG1zA";
var variantClassNames = {
	bU2JKRFEH: "framer-v-1szm6fu",
	gKiP_vGWQ: "framer-v-v0f6ug",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "bU2JKRFEH",
	Phone: "gKiP_vGWQ",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "bU2JKRFEH",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "bU2JKRFEH",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={"mailto:nayeemurrsakib@gmail.com"}
						nodeId={"bU2JKRFEH"}
						openInNewTab={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-1szm6fu", className2, classNames)} framer-16f1p70`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"bU2JKRFEH"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"bU2JKRFEH-hover": {
										"data-framer-name": void 0,
									},
									gKiP_vGWQ: {
										"data-framer-name": "Phone",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1jd0wdn"}
								data-framer-name={"Desktop"}
								layoutDependency={layoutDependency}
								layoutId={"BNmEM7Eav"}
							>
								<SVG
									className={"framer-1t56rn1"}
									data-framer-name={"ArrowElbowDownRight"}
									fill={
										'var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23)) /* {"name":"Black"} */'
									}
									intrinsicHeight={40}
									intrinsicWidth={40}
									layoutDependency={layoutDependency}
									layoutId={"XcWO4POua"}
									style={{
										rotate: -45,
									}}
									svg={
										'<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_232_56)">\n<path d="M26.25 20L33.75 27.5L26.25 35" stroke="black" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M11.25 5V27.5H33.75" stroke="black" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_232_56">\n<rect width="40" height="40" fill="white"/>\n</clipPath>\n</defs>\n</svg>\n'
									}
									variants={{
										"bU2JKRFEH-hover": {
											rotate: 0,
										},
									}}
									withExternalLayout={true}
								/>
								<motion.div
									className={"framer-1jts3mf"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"NESubPY5o"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-107n14l"}
										data-framer-name={"Hello@sakib.com"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"hsBIr4yxJ"}
										style={{
											"--extracted-1eung3n":
												"var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23))",
											"--framer-paragraph-spacing": "0px",
											opacity: 1,
										}}
										variants={{
											"bU2JKRFEH-hover": {
												opacity: 0,
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h4
												className={"framer-styles-preset-1xx5m9h"}
												data-styles-preset={"AOVMb4XLP"}
												style={{
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23)))",
												}}
											>
												{"Hellonrsakib@gmail.com"}
											</motion.h4>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1poq85z"}
										data-framer-name={"Let's Talk"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"rYQoQlRj1"}
										style={{
											"--extracted-1eung3n":
												"var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23))",
											"--framer-paragraph-spacing": "0px",
											opacity: 0,
										}}
										transformTemplate={transformTemplate1}
										variants={{
											"bU2JKRFEH-hover": {
												opacity: 1,
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												"bU2JKRFEH-hover": {
													transformTemplate: void 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h4
												className={"framer-styles-preset-1xx5m9h"}
												data-styles-preset={"AOVMb4XLP"}
												style={{
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23)))",
												}}
											>
												{"Let's Talk"}
											</motion.h4>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1r9j76h"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"P1nlv3tb8"}
								style={{
									backgroundColor:
										"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
								}}
							/>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lG1zA.framer-16f1p70, .framer-lG1zA .framer-16f1p70 { display: block; }",
	".framer-lG1zA.framer-1szm6fu { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-lG1zA .framer-1jd0wdn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-lG1zA .framer-1t56rn1 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); position: relative; width: 32px; }",
	".framer-lG1zA .framer-1jts3mf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-lG1zA .framer-107n14l { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-lG1zA .framer-1poq85z { flex: none; height: auto; left: 0px; position: absolute; top: -58%; white-space: pre; width: auto; z-index: 1; }",
	".framer-lG1zA .framer-1r9j76h { flex: none; height: 2px; overflow: visible; position: relative; width: 410px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lG1zA.framer-1szm6fu, .framer-lG1zA .framer-1jd0wdn, .framer-lG1zA .framer-1jts3mf { gap: 0px; } .framer-lG1zA.framer-1szm6fu > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } .framer-lG1zA.framer-1szm6fu > :first-child, .framer-lG1zA .framer-1jts3mf > :first-child { margin-top: 0px; } .framer-lG1zA.framer-1szm6fu > :last-child, .framer-lG1zA .framer-1jts3mf > :last-child { margin-bottom: 0px; } .framer-lG1zA .framer-1jd0wdn > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-lG1zA .framer-1jd0wdn > :first-child { margin-left: 0px; } .framer-lG1zA .framer-1jd0wdn > :last-child { margin-right: 0px; } .framer-lG1zA .framer-1jts3mf > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	".framer-lG1zA.framer-v-v0f6ug.framer-1szm6fu { cursor: unset; }",
	".framer-lG1zA.framer-v-v0f6ug .framer-1t56rn1 { height: var(--framer-aspect-ratio-supported, 24px); width: 24px; }",
	".framer-lG1zA.framer-v-1szm6fu.hover .framer-1jd0wdn, .framer-lG1zA.framer-v-1szm6fu.hover .framer-1r9j76h { width: 298px; }",
	".framer-lG1zA.framer-v-1szm6fu.hover .framer-1jts3mf { width: 258px; }",
	".framer-lG1zA.framer-v-1szm6fu.hover .framer-107n14l { bottom: -52px; left: 0px; position: absolute; z-index: 1; }",
	".framer-lG1zA.framer-v-1szm6fu.hover .framer-1poq85z { left: unset; position: relative; top: unset; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css,
];
var FramerJhd9lh2J6 = withCSS(Component, css2, "framer-lG1zA");
var stdin_default = FramerJhd9lh2J6;
FramerJhd9lh2J6.displayName = "Footer/Email";
FramerJhd9lh2J6.defaultProps = {
	height: 45,
	width: 410,
};
addPropertyControls(FramerJhd9lh2J6, {
	variant: {
		options: ["bU2JKRFEH", "gKiP_vGWQ"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerJhd9lh2J6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer/email
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "gKiP_vGWQ",
	md: "bU2JKRFEH",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var email_default = ComponentWithRoot;
export { email_default as default };
