// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import { Icon } from "../chunks/chunk-ELYQXSRD.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:button/cute-small-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wH7XIPl3YYfQe2bfPh8v/yU1IIR1oUDvUDO4z57xY/b2wZ7sU7q.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	gJgOVfifo: {
		hover: true,
	},
	NxzOy7ZTz: {
		hover: true,
	},
	OOE2Ht0K1: {
		hover: true,
	},
};
var cycleOrder = [
	"gJgOVfifo",
	"NxzOy7ZTz",
	"wxrX81Nw5",
	"VhTUcoor_",
	"OOE2Ht0K1",
];
var serializationHash = "framer-CuK2A";
var variantClassNames = {
	gJgOVfifo: "framer-v-p07qbz",
	NxzOy7ZTz: "framer-v-jl4koy",
	OOE2Ht0K1: "framer-v-me7g9b",
	VhTUcoor_: "framer-v-w8rgw9",
	wxrX81Nw5: "framer-v-rakbr6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 600,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	404: "NxzOy7ZTz",
	"For Templates": "OOE2Ht0K1",
	"Mobile 404": "VhTUcoor_",
	Main: "gJgOVfifo",
	Mobile: "wxrX81Nw5",
};
var getProps = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		D5f60bW5q: link ?? props.D5f60bW5q,
		QXsX1ABH_: title ?? props.QXsX1ABH_ ?? "Back",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "gJgOVfifo",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		D5f60bW5q,
		QXsX1ABH_,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "gJgOVfifo",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={D5f60bW5q}
						motionChild={true}
						nodeId={"gJgOVfifo"}
						scopeId={"b2wZ7sU7q"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-p07qbz", className, classNames)} framer-1o72bas`}
							data-border={true}
							data-framer-name={"Main"}
							layoutDependency={layoutDependency}
							layoutId={"gJgOVfifo"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgb(226, 225, 217)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								boxShadow: "none",
								...style,
							}}
							variants={{
								"gJgOVfifo-hover": {
									backgroundColor:
										"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									boxShadow: "none",
								},
								"NxzOy7ZTz-hover": {
									backgroundColor:
										"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									boxShadow: "none",
								},
								OOE2Ht0K1: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor:
										"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									boxShadow: "1px 2px 10px 0px rgba(0, 0, 0, 0.1)",
								},
							}}
							{...addPropertyOverrides(
								{
									"gJgOVfifo-hover": {
										"data-framer-name": void 0,
									},
									"NxzOy7ZTz-hover": {
										"data-framer-name": void 0,
									},
									"OOE2Ht0K1-hover": {
										"data-framer-name": void 0,
									},
									NxzOy7ZTz: {
										"data-framer-name": "404",
									},
									OOE2Ht0K1: {
										"data-framer-name": "For Templates",
									},
									VhTUcoor_: {
										"data-framer-name": "Mobile 404",
									},
									wxrX81Nw5: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1nu7jfq"}
								data-framer-name={"Icon Container"}
								layoutDependency={layoutDependency}
								layoutId={"E7V1pQ2GX"}
								style={{
									backgroundColor:
										"var(--token-403f5250-c23f-4327-bcf3-4fb3df82b8c0, rgb(226, 225, 217))",
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
								}}
								variants={{
									"gJgOVfifo-hover": {
										backgroundColor:
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
									"NxzOy7ZTz-hover": {
										backgroundColor:
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
									NxzOy7ZTz: {
										backgroundColor:
											"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									},
									OOE2Ht0K1: {
										backgroundColor:
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
									VhTUcoor_: {
										backgroundColor:
											"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									},
								}}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-j6wkn7-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"rMoDLC0iI-container"}
										nodeId={"rMoDLC0iI"}
										rendersWithMotion={true}
										scopeId={"b2wZ7sU7q"}
									>
										<Icon
											color={
												"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"ArrowLeft"}
											id={"rMoDLC0iI"}
											layoutId={"rMoDLC0iI"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"bold"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													"gJgOVfifo-hover": {
														color:
															"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
													},
													"NxzOy7ZTz-hover": {
														color:
															"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
													},
													"OOE2Ht0K1-hover": {
														color:
															"var(--token-403f5250-c23f-4327-bcf3-4fb3df82b8c0, rgb(226, 225, 217))",
													},
													NxzOy7ZTz: {
														iconSelection: "SmileySad",
													},
													OOE2Ht0K1: {
														color:
															"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
														iconSelection: "ShoppingCart",
														weight: "regular",
													},
													VhTUcoor_: {
														iconSelection: "SmileySad",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-md9ugo"}
								data-framer-name={"Back"}
								fonts={["GF;DM Sans-500"]}
								layoutDependency={layoutDependency}
								layoutId={"IqhaA1d4W"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={QXsX1ABH_}
								variants={{
									"OOE2Ht0K1-hover": {
										"--extracted-r6o4lv":
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"OOE2Ht0K1-hover": {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7RE0gU2Fucy01MDA=",
															"--framer-font-family":
																'"DM Sans", "DM Sans Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "500",
															"--framer-letter-spacing": "0.01em",
															"--framer-line-height": "160%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
														}}
													>
														{"Back"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7RE0gU2Fucy01MDA=",
											"--framer-font-family":
												'"DM Sans", "DM Sans Placeholder", sans-serif',
											"--framer-font-size": "14px",
											"--framer-font-weight": "500",
											"--framer-letter-spacing": "0.01em",
											"--framer-line-height": "160%",
										}}
									>
										{"Back"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-CuK2A.framer-1o72bas, .framer-CuK2A .framer-1o72bas { display: block; }",
	".framer-CuK2A.framer-p07qbz { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 4px 8px 4px 4px; position: relative; text-decoration: none; width: min-content; }",
	".framer-CuK2A .framer-1nu7jfq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 20px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 20px; }",
	".framer-CuK2A .framer-j6wkn7-container { flex: none; height: 12px; position: relative; width: 12px; }",
	".framer-CuK2A .framer-md9ugo { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-CuK2A.framer-p07qbz, .framer-CuK2A .framer-1nu7jfq { gap: 0px; } .framer-CuK2A.framer-p07qbz > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-CuK2A.framer-p07qbz > :first-child, .framer-CuK2A .framer-1nu7jfq > :first-child { margin-left: 0px; } .framer-CuK2A.framer-p07qbz > :last-child, .framer-CuK2A .framer-1nu7jfq > :last-child { margin-right: 0px; } .framer-CuK2A .framer-1nu7jfq > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } }",
	".framer-CuK2A.framer-v-rakbr6.framer-p07qbz, .framer-CuK2A.framer-v-w8rgw9.framer-p07qbz { cursor: unset; }",
	".framer-CuK2A.framer-v-me7g9b.framer-p07qbz { gap: 12px; justify-content: center; padding: 6px 6px 6px 12px; }",
	".framer-CuK2A.framer-v-me7g9b .framer-1nu7jfq { order: 1; }",
	".framer-CuK2A.framer-v-me7g9b .framer-md9ugo { order: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-CuK2A.framer-v-me7g9b.framer-p07qbz { gap: 0px; } .framer-CuK2A.framer-v-me7g9b.framer-p07qbz > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-CuK2A.framer-v-me7g9b.framer-p07qbz > :first-child { margin-left: 0px; } .framer-CuK2A.framer-v-me7g9b.framer-p07qbz > :last-child { margin-right: 0px; } }",
	'.framer-CuK2A[data-border="true"]::after, .framer-CuK2A [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerb2wZ7sU7q = withCSS(Component, css, "framer-CuK2A");
var stdin_default = Framerb2wZ7sU7q;
Framerb2wZ7sU7q.displayName = "Button/Cute Small Button";
Framerb2wZ7sU7q.defaultProps = {
	height: 30,
	width: 69,
};
addPropertyControls(Framerb2wZ7sU7q, {
	variant: {
		options: ["gJgOVfifo", "NxzOy7ZTz", "wxrX81Nw5", "VhTUcoor_", "OOE2Ht0K1"],
		optionTitles: ["Main", "404", "Mobile", "Mobile 404", "For Templates"],
		title: "Variant",
		type: ControlType.Enum,
	},
	D5f60bW5q: {
		title: "Link",
		type: ControlType.Link,
	},
	QXsX1ABH_: {
		defaultValue: "Back",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	Framerb2wZ7sU7q,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "DM Sans",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
					weight: "500",
				},
			],
		},
		...PhosphorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button/cute-small-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "VhTUcoor_",
	xl: "NxzOy7ZTz",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var cute_small_button_default = ComponentWithRoot;
export { cute_small_button_default as default };
