// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import { className, css, fonts } from "../chunks/chunk-SJ4Y2L4N.js";
import { Icon } from "../chunks/chunk-ELYQXSRD.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:button/primary-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rQUsS9zX9ZMfXax9Y5wr/ERfeACJrmVdIVgGnUOzf/HZ3RLe2rB.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	ITobNpQrN: {
		hover: true,
	},
	oup2Dy4oJ: {
		hover: true,
	},
};
var cycleOrder = ["ITobNpQrN", "oup2Dy4oJ", "GGS5UqZTL", "GbTNUDc5G"];
var serializationHash = "framer-cTloK";
var variantClassNames = {
	GbTNUDc5G: "framer-v-1sanpe8",
	GGS5UqZTL: "framer-v-12sr5o2",
	ITobNpQrN: "framer-v-11ulfto",
	oup2Dy4oJ: "framer-v-1l1zvq2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 70,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Mobile Secondary": "GbTNUDc5G",
	Mobile: "GGS5UqZTL",
	Primary: "ITobNpQrN",
	Secondary: "oup2Dy4oJ",
};
var getProps = ({ height, id, label, link, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		Cprqi0hWm:
			(_ref = label !== null && label !== void 0 ? label : props.Cprqi0hWm) !==
				null && _ref !== void 0
				? _ref
				: "View all Cases",
		dbCMAqs0u: link !== null && link !== void 0 ? link : props.dbCMAqs0u,
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "ITobNpQrN",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Cprqi0hWm,
		dbCMAqs0u,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ITobNpQrN",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={dbCMAqs0u}
						nodeId={"ITobNpQrN"}
						{...addPropertyOverrides(
							{
								GbTNUDc5G: {
									href: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-11ulfto", className2, classNames)} framer-1k8i9w`}
							data-border={true}
							data-framer-name={"Primary"}
							layoutDependency={layoutDependency}
							layoutId={"ITobNpQrN"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgb(226, 225, 217)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
								borderBottomLeftRadius: 90,
								borderBottomRightRadius: 90,
								borderTopLeftRadius: 90,
								borderTopRightRadius: 90,
								...style,
							}}
							variants={{
								"ITobNpQrN-hover": {
									"--border-color": "rgba(227, 226, 218, 0)",
									backgroundColor:
										"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
								},
								"oup2Dy4oJ-hover": {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor:
										"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
								},
								GbTNUDc5G: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor:
										"var(--token-403f5250-c23f-4327-bcf3-4fb3df82b8c0, rgb(226, 225, 217))",
								},
								oup2Dy4oJ: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor:
										"var(--token-403f5250-c23f-4327-bcf3-4fb3df82b8c0, rgb(226, 225, 217))",
								},
							}}
							{...addPropertyOverrides(
								{
									"ITobNpQrN-hover": {
										"data-framer-name": void 0,
									},
									"oup2Dy4oJ-hover": {
										"data-framer-name": void 0,
									},
									GbTNUDc5G: {
										"data-framer-name": "Mobile Secondary",
									},
									GGS5UqZTL: {
										"data-framer-name": "Mobile",
									},
									oup2Dy4oJ: {
										"data-framer-name": "Secondary",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-13a23m7"}
								data-framer-name={"View Full Project"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"hCby_rjNz"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={Cprqi0hWm}
								variants={{
									"ITobNpQrN-hover": {
										"--extracted-r6o4lv":
											"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									},
									"oup2Dy4oJ-hover": {
										"--extracted-r6o4lv":
											"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"ITobNpQrN-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-9w7x32"}
														data-styles-preset={"dKg4d4Wgl"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161)))",
														}}
													>
														{"View all Cases"}
													</motion.p>
												</React.Fragment>
											),
										},
										"oup2Dy4oJ-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-9w7x32"}
														data-styles-preset={"dKg4d4Wgl"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161)))",
														}}
													>
														{"View all Cases"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-9w7x32"}
										data-styles-preset={"dKg4d4Wgl"}
									>
										{"View all Cases"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-g0bb1a"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"xaopByJVG"}
								style={{
									backgroundColor:
										"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									borderBottomLeftRadius: 90,
									borderBottomRightRadius: 90,
									borderTopLeftRadius: 90,
									borderTopRightRadius: 90,
								}}
								variants={{
									"ITobNpQrN-hover": {
										backgroundColor:
											"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									},
									"oup2Dy4oJ-hover": {
										backgroundColor:
											"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									},
								}}
							>
								<ComponentViewportProvider>
									<motion.div
										className={"framer-10trfio-container"}
										layoutDependency={layoutDependency}
										layoutId={"VVs9qHHjk-container"}
										style={{
											rotate: 0,
										}}
										variants={{
											"ITobNpQrN-hover": {
												rotate: 45,
											},
											"oup2Dy4oJ-hover": {
												rotate: 45,
											},
										}}
									>
										<Icon
											color={
												"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"ArrowElbowRight"}
											id={"VVs9qHHjk"}
											layoutId={"VVs9qHHjk"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"bold"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													"ITobNpQrN-hover": {
														color:
															"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
													},
													"oup2Dy4oJ-hover": {
														color:
															"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</motion.div>
								</ComponentViewportProvider>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-cTloK.framer-1k8i9w, .framer-cTloK .framer-1k8i9w { display: block; }",
	".framer-cTloK.framer-11ulfto { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 8px 8px 8px 32px; position: relative; text-decoration: none; width: 756px; will-change: var(--framer-will-change-override, transform); }",
	".framer-cTloK .framer-13a23m7 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-cTloK .framer-g0bb1a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 32px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 32px; z-index: 1; }",
	".framer-cTloK .framer-10trfio-container { flex: none; height: 20px; position: relative; width: 16px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cTloK .framer-g0bb1a { gap: 0px; } .framer-cTloK .framer-g0bb1a > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-cTloK .framer-g0bb1a > :first-child { margin-left: 0px; } .framer-cTloK .framer-g0bb1a > :last-child { margin-right: 0px; } }",
	".framer-cTloK.framer-v-12sr5o2.framer-11ulfto, .framer-cTloK.framer-v-1sanpe8.framer-11ulfto { cursor: unset; }",
	".framer-cTloK.framer-v-11ulfto.hover .framer-13a23m7 { order: 0; }",
	".framer-cTloK.framer-v-11ulfto.hover .framer-g0bb1a { order: 1; }",
	...css,
	'.framer-cTloK[data-border="true"]::after, .framer-cTloK [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerHZ3RLe2rB = withCSS(Component, css2, "framer-cTloK");
var stdin_default = FramerHZ3RLe2rB;
FramerHZ3RLe2rB.displayName = "Button/Primary Button";
FramerHZ3RLe2rB.defaultProps = {
	height: 48,
	width: 756,
};
addPropertyControls(FramerHZ3RLe2rB, {
	variant: {
		options: ["ITobNpQrN", "oup2Dy4oJ", "GGS5UqZTL", "GbTNUDc5G"],
		optionTitles: ["Primary", "Secondary", "Mobile", "Mobile Secondary"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Cprqi0hWm: {
		defaultValue: "View all Cases",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
	dbCMAqs0u: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerHZ3RLe2rB,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button/primary-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GGS5UqZTL",
	xl: "ITobNpQrN",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var primary_button_default = ComponentWithRoot;
export { primary_button_default as default };
