// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import { stdin_default, stdin_default2 } from "../chunks/chunk-S34F5IYF.js";
import "../chunks/chunk-SJ4Y2L4N.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:navigation/full-menu
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6hmU4fLvz7FRPgGs5yqz/77Z0PEimJ9tvM2GYN0aO/ifb1Ncyh9.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var NavigationMenuFonts = getFonts(stdin_default);
var NavigationNavItemFonts = getFonts(stdin_default2);
var cycleOrder = ["KHtbqq85K", "evP2QilGJ", "d1YAUe7y8", "S_Gi64qYA"];
var serializationHash = "framer-Fescw";
var variantClassNames = {
	d1YAUe7y8: "framer-v-5y8xaq",
	evP2QilGJ: "framer-v-2bp8y4",
	KHtbqq85K: "framer-v-wphql8",
	S_Gi64qYA: "framer-v-32wc65",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 600,
	type: "spring",
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 0.1,
	stiffness: 546,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Mobile open": "S_Gi64qYA",
	Close: "KHtbqq85K",
	Mobile: "d1YAUe7y8",
	Open: "evP2QilGJ",
};
var getProps = ({
	height,
	id,
	link01,
	link02,
	link03,
	link04,
	pageNames01,
	pageNames02,
	pageNames03,
	pageNames04,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		CBX0MYr_6:
			(_ref =
				pageNames01 !== null && pageNames01 !== void 0
					? pageNames01
					: props.CBX0MYr_6) !== null && _ref !== void 0
				? _ref
				: "About",
		D29tSpr5W: link04 !== null && link04 !== void 0 ? link04 : props.D29tSpr5W,
		fnTPRPrm9: link01 !== null && link01 !== void 0 ? link01 : props.fnTPRPrm9,
		fxifn0tt_:
			(_ref1 =
				pageNames03 !== null && pageNames03 !== void 0
					? pageNames03
					: props.fxifn0tt_) !== null && _ref1 !== void 0
				? _ref1
				: "Thoughts",
		PUl9fstAh:
			(_ref2 =
				pageNames02 !== null && pageNames02 !== void 0
					? pageNames02
					: props.PUl9fstAh) !== null && _ref2 !== void 0
				? _ref2
				: "Cases",
		PvLdBEHqU:
			(_ref3 =
				pageNames04 !== null && pageNames04 !== void 0
					? pageNames04
					: props.PvLdBEHqU) !== null && _ref3 !== void 0
				? _ref3
				: "Contact",
		sJUZJ7R37: link03 !== null && link03 !== void 0 ? link03 : props.sJUZJ7R37,
		SuYvin8wV: link02 !== null && link02 !== void 0 ? link02 : props.SuYvin8wV,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "KHtbqq85K",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		CBX0MYr_6,
		fnTPRPrm9,
		PUl9fstAh,
		SuYvin8wV,
		fxifn0tt_,
		sJUZJ7R37,
		PvLdBEHqU,
		D29tSpr5W,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KHtbqq85K",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapzoodax = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("evP2QilGJ");
	});
	const onTapfdcd1p = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("S_Gi64qYA");
	});
	const V01g6WIArsnz0md = activeVariantCallback(async (...args) => {
		setVariant("evP2QilGJ");
	});
	const V01g6WIAr1pe3rd9 = activeVariantCallback(async (...args) => {
		setVariant("KHtbqq85K");
	});
	const V01g6WIAr1phbw4r = activeVariantCallback(async (...args) => {
		setVariant("d1YAUe7y8");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							evP2QilGJ: {
								value: transition2,
							},
							S_Gi64qYA: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-wphql8",
							className,
							classNames,
						)}
						data-framer-name={"Close"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"KHtbqq85K"}
						onTap={onTapzoodax}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								d1YAUe7y8: {
									"data-framer-name": "Mobile",
									onTap: onTapfdcd1p,
								},
								evP2QilGJ: {
									"data-framer-name": "Open",
									"data-highlight": void 0,
									onTap: void 0,
								},
								S_Gi64qYA: {
									"data-framer-name": "Mobile open",
									"data-highlight": void 0,
									onTap: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={38}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								0
							}
						>
							<motion.div
								className={"framer-n0i41v-container"}
								layoutDependency={layoutDependency}
								layoutId={"H4s6oHxZv-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "H4s6oHxZv",
									layoutId: "H4s6oHxZv",
									V01g6WIAr: V01g6WIArsnz0md,
									variant: "GdJQjNPrY",
									width: "100%",
									...addPropertyOverrides(
										{
											d1YAUe7y8: {
												variant: "n228dMgEE",
											},
											evP2QilGJ: {
												V01g6WIAr: V01g6WIAr1pe3rd9,
												variant: "gYD3zlIbc",
											},
											S_Gi64qYA: {
												V01g6WIAr: V01g6WIAr1phbw4r,
												variant: "gYD3zlIbc",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) + -436
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											46,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											46,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-xflvgs-container"}
								layoutDependency={layoutDependency}
								layoutId={"ETzUWqd4H-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "ETzUWqd4H",
									layoutId: "ETzUWqd4H",
									qg9thEk2O: "About",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: CBX0MYr_6,
												sDHQdK2Y_: fnTPRPrm9,
											},
											S_Gi64qYA: {
												qg9thEk2O: CBX0MYr_6,
												sDHQdK2Y_: fnTPRPrm9,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) + -336
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											96,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											96,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-7h0vk4-container"}
								layoutDependency={layoutDependency}
								layoutId={"q_eWTY4Xv-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "q_eWTY4Xv",
									layoutId: "q_eWTY4Xv",
									qg9thEk2O: "Work",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: PUl9fstAh,
												sDHQdK2Y_: SuYvin8wV,
											},
											S_Gi64qYA: {
												qg9thEk2O: PUl9fstAh,
												sDHQdK2Y_: SuYvin8wV,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) + -196
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											146,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											146,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-125srf0-container"}
								layoutDependency={layoutDependency}
								layoutId={"ca7DnWNsQ-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "ca7DnWNsQ",
									layoutId: "ca7DnWNsQ",
									qg9thEk2O: "Blog",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: fxifn0tt_,
												sDHQdK2Y_: sJUZJ7R37,
											},
											S_Gi64qYA: {
												qg9thEk2O: fxifn0tt_,
												sDHQdK2Y_: sJUZJ7R37,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.height) || 38) -
								42
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											196,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											196,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-7s5u4v-container"}
								layoutDependency={layoutDependency}
								layoutId={"m_qVv1rY9-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "m_qVv1rY9",
									layoutId: "m_qVv1rY9",
									qg9thEk2O: "Contact",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: PvLdBEHqU,
												sDHQdK2Y_: D29tSpr5W,
											},
											S_Gi64qYA: {
												qg9thEk2O: PvLdBEHqU,
												sDHQdK2Y_: D29tSpr5W,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Fescw.framer-dnkifl, .framer-Fescw .framer-dnkifl { display: block; }",
	".framer-Fescw.framer-wphql8 { align-content: flex-end; align-items: flex-end; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-Fescw .framer-n0i41v-container { flex: none; height: auto; position: relative; width: auto; z-index: 3; }",
	".framer-Fescw .framer-xflvgs-container { flex: none; height: auto; position: absolute; right: 0px; top: -436px; width: auto; z-index: 1; }",
	".framer-Fescw .framer-7h0vk4-container { flex: none; height: auto; position: absolute; right: 0px; top: -336px; width: auto; z-index: 1; }",
	".framer-Fescw .framer-125srf0-container { flex: none; height: auto; position: absolute; right: 0px; top: -196px; width: auto; z-index: 1; }",
	".framer-Fescw .framer-7s5u4v-container { bottom: 0px; flex: none; height: auto; position: absolute; right: 0px; width: auto; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Fescw.framer-wphql8 { gap: 0px; } .framer-Fescw.framer-wphql8 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-Fescw.framer-wphql8 > :first-child { margin-top: 0px; } .framer-Fescw.framer-wphql8 > :last-child { margin-bottom: 0px; } }",
	".framer-Fescw.framer-v-2bp8y4.framer-wphql8, .framer-Fescw.framer-v-32wc65.framer-wphql8 { cursor: unset; }",
	".framer-Fescw.framer-v-2bp8y4 .framer-xflvgs-container, .framer-Fescw.framer-v-2bp8y4 .framer-7h0vk4-container, .framer-Fescw.framer-v-2bp8y4 .framer-125srf0-container, .framer-Fescw.framer-v-32wc65 .framer-xflvgs-container, .framer-Fescw.framer-v-32wc65 .framer-7h0vk4-container, .framer-Fescw.framer-v-32wc65 .framer-125srf0-container { position: relative; right: unset; top: unset; z-index: 2; }",
	".framer-Fescw.framer-v-2bp8y4 .framer-7s5u4v-container, .framer-Fescw.framer-v-32wc65 .framer-7s5u4v-container { bottom: unset; position: relative; right: unset; z-index: 2; }",
];
var Framerifb1Ncyh9 = withCSS(Component, css, "framer-Fescw");
var stdin_default3 = Framerifb1Ncyh9;
Framerifb1Ncyh9.displayName = "Navigation/Full Menu";
Framerifb1Ncyh9.defaultProps = {
	height: 38,
	width: 125,
};
addPropertyControls(Framerifb1Ncyh9, {
	variant: {
		options: ["KHtbqq85K", "evP2QilGJ", "d1YAUe7y8", "S_Gi64qYA"],
		optionTitles: ["Close", "Open", "Mobile", "Mobile open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	CBX0MYr_6: {
		defaultValue: "About",
		displayTextArea: false,
		title: "Page names 01",
		type: ControlType.String,
	},
	fnTPRPrm9: {
		title: "Link 01",
		type: ControlType.Link,
	},
	PUl9fstAh: {
		defaultValue: "Cases",
		displayTextArea: false,
		title: "Page names 02",
		type: ControlType.String,
	},
	SuYvin8wV: {
		title: "Link 02",
		type: ControlType.Link,
	},
	fxifn0tt_: {
		defaultValue: "Thoughts",
		displayTextArea: false,
		title: "Page names 03",
		type: ControlType.String,
	},
	sJUZJ7R37: {
		title: "Link 03",
		type: ControlType.Link,
	},
	PvLdBEHqU: {
		defaultValue: "Contact",
		displayTextArea: false,
		title: "Page names 04",
		type: ControlType.String,
	},
	D29tSpr5W: {
		title: "Link 04",
		type: ControlType.Link,
	},
});
addFonts(
	Framerifb1Ncyh9,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...NavigationMenuFonts,
		...NavigationNavItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/full-menu
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KHtbqq85K",
	sm: "d1YAUe7y8",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var full_menu_default = ComponentWithRoot;
export { full_menu_default as default };
