// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import { className, css, fonts } from "../chunks/chunk-SJ4Y2L4N.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:navigation/menu
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jZrh8godfS77oYkhc7h7/YElDYtFGZ18HP1Cn1XuS/lzvsgUTYy.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	GdJQjNPrY: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = ["GdJQjNPrY", "gYD3zlIbc", "n228dMgEE"];
var serializationHash = "framer-FdCQT";
var variantClassNames = {
	GdJQjNPrY: "framer-v-1f6ycid",
	gYD3zlIbc: "framer-v-1uj9xqn",
	n228dMgEE: "framer-v-lxzkvm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "GdJQjNPrY",
	Mobile: "n228dMgEE",
	Open: "gYD3zlIbc",
};
var getProps = ({ click, height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		V01g6WIAr: click !== null && click !== void 0 ? click : props.V01g6WIAr,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "GdJQjNPrY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		V01g6WIAr,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "GdJQjNPrY",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1lmz781 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (V01g6WIAr) {
			const res = await V01g6WIAr(...args);
			if (res === false) return false;
		}
	});
	const onTap1wvqoh5 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (V01g6WIAr) {
			const res = await V01g6WIAr(...args);
			if (res === false) return false;
		}
		setVariant("gYD3zlIbc");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1f6ycid",
							className2,
							classNames,
						)}
						data-framer-name={"Close"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"GdJQjNPrY"}
						onTap={onTap1lmz781}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backdropFilter: "blur(5px)",
							backgroundColor:
								"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
							borderBottomLeftRadius: 22,
							borderBottomRightRadius: 22,
							borderTopLeftRadius: 22,
							borderTopRightRadius: 22,
							WebkitBackdropFilter: "blur(5px)",
							...style,
						}}
						variants={{
							"GdJQjNPrY-hover": {
								backgroundColor:
									"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
							},
							"GdJQjNPrY-pressed": {
								backgroundColor:
									"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
							},
						}}
						{...addPropertyOverrides(
							{
								"GdJQjNPrY-hover": {
									"data-framer-name": void 0,
								},
								"GdJQjNPrY-pressed": {
									"data-framer-name": void 0,
								},
								gYD3zlIbc: {
									"data-framer-name": "Open",
								},
								n228dMgEE: {
									"data-framer-name": "Mobile",
									onTap: onTap1wvqoh5,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-8jxbo5"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"G1GUYFr_6"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							variants={{
								"GdJQjNPrY-hover": {
									"--extracted-r6o4lv":
										"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
								},
								"GdJQjNPrY-pressed": {
									"--extracted-r6o4lv":
										"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									"GdJQjNPrY-hover": {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-9w7x32"}
													data-styles-preset={"dKg4d4Wgl"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
													}}
												>
													{"Menu"}
												</motion.p>
											</React.Fragment>
										),
									},
									"GdJQjNPrY-pressed": {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-9w7x32"}
													data-styles-preset={"dKg4d4Wgl"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
													}}
												>
													{"Menu"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-9w7x32"}
									data-styles-preset={"dKg4d4Wgl"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161)))",
									}}
								>
									{"Menu"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-156fuuh"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"gv5EwBFyM"}
						>
							<motion.div
								className={"framer-a4myg8"}
								layoutDependency={layoutDependency}
								layoutId={"MgIguTB5B"}
								style={{
									backgroundColor:
										"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									borderBottomLeftRadius: 900,
									borderBottomRightRadius: 900,
									borderTopLeftRadius: 900,
									borderTopRightRadius: 900,
									rotate: 0,
								}}
								variants={{
									"GdJQjNPrY-hover": {
										backgroundColor:
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
									"GdJQjNPrY-pressed": {
										backgroundColor:
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
									gYD3zlIbc: {
										rotate: 45,
									},
								}}
							/>
							<motion.div
								className={"framer-hg0nxl"}
								layoutDependency={layoutDependency}
								layoutId={"GTH37B9p6"}
								style={{
									backgroundColor:
										"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
									borderBottomLeftRadius: 900,
									borderBottomRightRadius: 900,
									borderTopLeftRadius: 900,
									borderTopRightRadius: 900,
									rotate: 0,
								}}
								variants={{
									"GdJQjNPrY-hover": {
										backgroundColor:
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
									"GdJQjNPrY-pressed": {
										backgroundColor:
											"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
									},
									gYD3zlIbc: {
										rotate: -45,
									},
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FdCQT.framer-19fw69v, .framer-FdCQT .framer-19fw69v { display: block; }",
	".framer-FdCQT.framer-1f6ycid { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 8px 32px 8px 32px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-FdCQT .framer-8jxbo5 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-FdCQT .framer-156fuuh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: 20px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 20px; }",
	".framer-FdCQT .framer-a4myg8, .framer-FdCQT .framer-hg0nxl { flex: none; height: 2px; overflow: hidden; position: relative; width: 16px; will-change: var(--framer-will-change-override, transform); }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FdCQT.framer-1f6ycid, .framer-FdCQT .framer-156fuuh { gap: 0px; } .framer-FdCQT.framer-1f6ycid > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } .framer-FdCQT.framer-1f6ycid > :first-child { margin-left: 0px; } .framer-FdCQT.framer-1f6ycid > :last-child { margin-right: 0px; } .framer-FdCQT .framer-156fuuh > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } .framer-FdCQT .framer-156fuuh > :first-child { margin-top: 0px; } .framer-FdCQT .framer-156fuuh > :last-child { margin-bottom: 0px; } }",
	".framer-FdCQT.framer-v-1uj9xqn .framer-hg0nxl { left: calc(50.00000000000002% - 16px / 2); position: absolute; top: calc(50.00000000000002% - 2px / 2); z-index: 1; }",
	...css,
];
var FramerlzvsgUTYy = withCSS(Component, css2, "framer-FdCQT");
var stdin_default = FramerlzvsgUTYy;
FramerlzvsgUTYy.displayName = "Navigation/Menu";
FramerlzvsgUTYy.defaultProps = {
	height: 38,
	width: 125,
};
addPropertyControls(FramerlzvsgUTYy, {
	variant: {
		options: ["GdJQjNPrY", "gYD3zlIbc", "n228dMgEE"],
		optionTitles: ["Close", "Open", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	V01g6WIAr: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerlzvsgUTYy,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/menu
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GdJQjNPrY",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var menu_default = ComponentWithRoot;
export { menu_default as default };
