// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import { stdin_default, stdin_default2 } from "../chunks/chunk-S34F5IYF.js";
import {
	className as className2,
	className2 as className3,
	css as css2,
	css2 as css3,
	fonts as fonts2,
	fonts2 as fonts3,
} from "../chunks/chunk-TWBPDT67.js";
import { className, css, fonts } from "../chunks/chunk-SJ4Y2L4N.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:navigation/nav-bar
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6soyjxavJuR89QnNrSZN/SFDfpFDiqHBRN4NBYkiT/tCo4ObWfx.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	Link,
	ResolveLinks,
	RichText,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/ERLjEfSUjEZzmzi5ATwn/MJqPbqKhn8o4YnRZB8VL/ifb1Ncyh9.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var NavigationMenuFonts = getFonts(stdin_default);
var NavigationNavItemFonts = getFonts(stdin_default2);
var cycleOrder = ["KHtbqq85K", "evP2QilGJ", "d1YAUe7y8", "S_Gi64qYA"];
var serializationHash = "framer-Fescw";
var variantClassNames = {
	d1YAUe7y8: "framer-v-5y8xaq",
	evP2QilGJ: "framer-v-2bp8y4",
	KHtbqq85K: "framer-v-wphql8",
	S_Gi64qYA: "framer-v-32wc65",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 600,
	type: "spring",
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 0.1,
	stiffness: 546,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Mobile open": "S_Gi64qYA",
	Close: "KHtbqq85K",
	Mobile: "d1YAUe7y8",
	Open: "evP2QilGJ",
};
var getProps = ({
	height,
	id,
	link01,
	link02,
	link03,
	link04,
	pageNames01,
	pageNames02,
	pageNames03,
	pageNames04,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		CBX0MYr_6:
			(_ref =
				pageNames01 !== null && pageNames01 !== void 0
					? pageNames01
					: props.CBX0MYr_6) !== null && _ref !== void 0
				? _ref
				: "About",
		D29tSpr5W: link04 !== null && link04 !== void 0 ? link04 : props.D29tSpr5W,
		fnTPRPrm9: link01 !== null && link01 !== void 0 ? link01 : props.fnTPRPrm9,
		fxifn0tt_:
			(_ref1 =
				pageNames03 !== null && pageNames03 !== void 0
					? pageNames03
					: props.fxifn0tt_) !== null && _ref1 !== void 0
				? _ref1
				: "Thoughts",
		PUl9fstAh:
			(_ref2 =
				pageNames02 !== null && pageNames02 !== void 0
					? pageNames02
					: props.PUl9fstAh) !== null && _ref2 !== void 0
				? _ref2
				: "Cases",
		PvLdBEHqU:
			(_ref3 =
				pageNames04 !== null && pageNames04 !== void 0
					? pageNames04
					: props.PvLdBEHqU) !== null && _ref3 !== void 0
				? _ref3
				: "Contact",
		sJUZJ7R37: link03 !== null && link03 !== void 0 ? link03 : props.sJUZJ7R37,
		SuYvin8wV: link02 !== null && link02 !== void 0 ? link02 : props.SuYvin8wV,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "KHtbqq85K",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		CBX0MYr_6,
		fnTPRPrm9,
		PUl9fstAh,
		SuYvin8wV,
		fxifn0tt_,
		sJUZJ7R37,
		PvLdBEHqU,
		D29tSpr5W,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KHtbqq85K",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapzoodax = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("evP2QilGJ");
	});
	const onTapfdcd1p = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("S_Gi64qYA");
	});
	const V01g6WIArsnz0md = activeVariantCallback(async (...args) => {
		setVariant("evP2QilGJ");
	});
	const V01g6WIAr1pe3rd9 = activeVariantCallback(async (...args) => {
		setVariant("KHtbqq85K");
	});
	const V01g6WIAr1phbw4r = activeVariantCallback(async (...args) => {
		setVariant("d1YAUe7y8");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							evP2QilGJ: {
								value: transition2,
							},
							S_Gi64qYA: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-wphql8",
							className4,
							classNames,
						)}
						data-framer-name={"Close"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"KHtbqq85K"}
						onTap={onTapzoodax}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								d1YAUe7y8: {
									"data-framer-name": "Mobile",
									onTap: onTapfdcd1p,
								},
								evP2QilGJ: {
									"data-framer-name": "Open",
									"data-highlight": void 0,
									onTap: void 0,
								},
								S_Gi64qYA: {
									"data-framer-name": "Mobile open",
									"data-highlight": void 0,
									onTap: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={38}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								0
							}
						>
							<motion.div
								className={"framer-n0i41v-container"}
								layoutDependency={layoutDependency}
								layoutId={"H4s6oHxZv-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "H4s6oHxZv",
									layoutId: "H4s6oHxZv",
									V01g6WIAr: V01g6WIArsnz0md,
									variant: "GdJQjNPrY",
									width: "100%",
									...addPropertyOverrides(
										{
											d1YAUe7y8: {
												variant: "n228dMgEE",
											},
											evP2QilGJ: {
												V01g6WIAr: V01g6WIAr1pe3rd9,
												variant: "gYD3zlIbc",
											},
											S_Gi64qYA: {
												V01g6WIAr: V01g6WIAr1phbw4r,
												variant: "gYD3zlIbc",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) + -436
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											46,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											46,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-xflvgs-container"}
								layoutDependency={layoutDependency}
								layoutId={"ETzUWqd4H-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "ETzUWqd4H",
									layoutId: "ETzUWqd4H",
									qg9thEk2O: "About",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: CBX0MYr_6,
												sDHQdK2Y_: fnTPRPrm9,
											},
											S_Gi64qYA: {
												qg9thEk2O: CBX0MYr_6,
												sDHQdK2Y_: fnTPRPrm9,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) + -336
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											96,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											96,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-7h0vk4-container"}
								layoutDependency={layoutDependency}
								layoutId={"q_eWTY4Xv-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "q_eWTY4Xv",
									layoutId: "q_eWTY4Xv",
									qg9thEk2O: "Work",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: PUl9fstAh,
												sDHQdK2Y_: SuYvin8wV,
											},
											S_Gi64qYA: {
												qg9thEk2O: PUl9fstAh,
												sDHQdK2Y_: SuYvin8wV,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) + -196
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											146,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											146,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-125srf0-container"}
								layoutDependency={layoutDependency}
								layoutId={"ca7DnWNsQ-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "ca7DnWNsQ",
									layoutId: "ca7DnWNsQ",
									qg9thEk2O: "Blog",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: fxifn0tt_,
												sDHQdK2Y_: sJUZJ7R37,
											},
											S_Gi64qYA: {
												qg9thEk2O: fxifn0tt_,
												sDHQdK2Y_: sJUZJ7R37,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={42}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.height) || 38) -
								42
							}
							{...addPropertyOverrides(
								{
									evP2QilGJ: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											196,
									},
									S_Gi64qYA: {
										y:
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											0 +
											196,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-7s5u4v-container"}
								layoutDependency={layoutDependency}
								layoutId={"m_qVv1rY9-container"}
								style={{
									opacity: 0,
								}}
								variants={{
									evP2QilGJ: {
										opacity: 1,
									},
									S_Gi64qYA: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "m_qVv1rY9",
									layoutId: "m_qVv1rY9",
									qg9thEk2O: "Contact",
									width: "100%",
									...addPropertyOverrides(
										{
											evP2QilGJ: {
												qg9thEk2O: PvLdBEHqU,
												sDHQdK2Y_: D29tSpr5W,
											},
											S_Gi64qYA: {
												qg9thEk2O: PvLdBEHqU,
												sDHQdK2Y_: D29tSpr5W,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Fescw.framer-dnkifl, .framer-Fescw .framer-dnkifl { display: block; }",
	".framer-Fescw.framer-wphql8 { align-content: flex-end; align-items: flex-end; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-Fescw .framer-n0i41v-container { flex: none; height: auto; position: relative; width: auto; z-index: 3; }",
	".framer-Fescw .framer-xflvgs-container { flex: none; height: auto; position: absolute; right: 0px; top: -436px; width: auto; z-index: 1; }",
	".framer-Fescw .framer-7h0vk4-container { flex: none; height: auto; position: absolute; right: 0px; top: -336px; width: auto; z-index: 1; }",
	".framer-Fescw .framer-125srf0-container { flex: none; height: auto; position: absolute; right: 0px; top: -196px; width: auto; z-index: 1; }",
	".framer-Fescw .framer-7s5u4v-container { bottom: 0px; flex: none; height: auto; position: absolute; right: 0px; width: auto; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Fescw.framer-wphql8 { gap: 0px; } .framer-Fescw.framer-wphql8 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-Fescw.framer-wphql8 > :first-child { margin-top: 0px; } .framer-Fescw.framer-wphql8 > :last-child { margin-bottom: 0px; } }",
	".framer-Fescw.framer-v-2bp8y4.framer-wphql8, .framer-Fescw.framer-v-32wc65.framer-wphql8 { cursor: unset; }",
	".framer-Fescw.framer-v-2bp8y4 .framer-xflvgs-container, .framer-Fescw.framer-v-2bp8y4 .framer-7h0vk4-container, .framer-Fescw.framer-v-2bp8y4 .framer-125srf0-container, .framer-Fescw.framer-v-32wc65 .framer-xflvgs-container, .framer-Fescw.framer-v-32wc65 .framer-7h0vk4-container, .framer-Fescw.framer-v-32wc65 .framer-125srf0-container { position: relative; right: unset; top: unset; z-index: 2; }",
	".framer-Fescw.framer-v-2bp8y4 .framer-7s5u4v-container, .framer-Fescw.framer-v-32wc65 .framer-7s5u4v-container { bottom: unset; position: relative; right: unset; z-index: 2; }",
];
var Framerifb1Ncyh9 = withCSS(Component, css4, "framer-Fescw");
var stdin_default3 = Framerifb1Ncyh9;
Framerifb1Ncyh9.displayName = "Navigation/Full Menu";
Framerifb1Ncyh9.defaultProps = {
	height: 38,
	width: 125,
};
addPropertyControls(Framerifb1Ncyh9, {
	variant: {
		options: ["KHtbqq85K", "evP2QilGJ", "d1YAUe7y8", "S_Gi64qYA"],
		optionTitles: ["Close", "Open", "Mobile", "Mobile open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	CBX0MYr_6: {
		defaultValue: "About",
		displayTextArea: false,
		title: "Page names 01",
		type: ControlType.String,
	},
	fnTPRPrm9: {
		title: "Link 01",
		type: ControlType.Link,
	},
	PUl9fstAh: {
		defaultValue: "Cases",
		displayTextArea: false,
		title: "Page names 02",
		type: ControlType.String,
	},
	SuYvin8wV: {
		title: "Link 02",
		type: ControlType.Link,
	},
	fxifn0tt_: {
		defaultValue: "Thoughts",
		displayTextArea: false,
		title: "Page names 03",
		type: ControlType.String,
	},
	sJUZJ7R37: {
		title: "Link 03",
		type: ControlType.Link,
	},
	PvLdBEHqU: {
		defaultValue: "Contact",
		displayTextArea: false,
		title: "Page names 04",
		type: ControlType.String,
	},
	D29tSpr5W: {
		title: "Link 04",
		type: ControlType.Link,
	},
});
addFonts(
	Framerifb1Ncyh9,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...NavigationMenuFonts,
		...NavigationNavItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/6soyjxavJuR89QnNrSZN/SFDfpFDiqHBRN4NBYkiT/tCo4ObWfx.js
var NavigationFullMenuFonts = getFonts2(stdin_default3);
var cycleOrder2 = [
	"Uq_535luA",
	"aySkskEZU",
	"RMl1e1nPM",
	"k_0ApqBeX",
	"yPIBc3G1h",
];
var serializationHash2 = "framer-p9S3Q";
var variantClassNames2 = {
	aySkskEZU: "framer-v-mxsttz",
	k_0ApqBeX: "framer-v-z7s0vp",
	RMl1e1nPM: "framer-v-1mwlzrf",
	Uq_535luA: "framer-v-18hy7lq",
	yPIBc3G1h: "framer-v-1wuo9mc",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition22 = {
	damping: 70,
	delay: 0,
	mass: 1,
	stiffness: 600,
	type: "spring",
};
var animation = {
	opacity: 0.7,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition22,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Desktop Small": "aySkskEZU",
	"Variant 5": "yPIBc3G1h",
	Desktop: "Uq_535luA",
	Phone: "k_0ApqBeX",
	Tablet: "RMl1e1nPM",
};
var getProps2 = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap2[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "Uq_535luA",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Uq_535luA",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const router = useRouter();
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [className, className3, className2];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.nav
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-18hy7lq",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Uq_535luA"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backdropFilter: "none",
							borderBottomLeftRadius: 0,
							borderBottomRightRadius: 0,
							borderTopLeftRadius: 0,
							borderTopRightRadius: 0,
							WebkitBackdropFilter: "none",
							...style,
						}}
						variants={{
							yPIBc3G1h: {
								backdropFilter: "blur(0px)",
								borderBottomLeftRadius: 26,
								borderBottomRightRadius: 26,
								borderTopLeftRadius: 26,
								borderTopRightRadius: 26,
								WebkitBackdropFilter: "blur(0px)",
							},
						}}
						{...addPropertyOverrides2(
							{
								aySkskEZU: {
									"data-framer-name": "Desktop Small",
								},
								k_0ApqBeX: {
									"data-framer-name": "Phone",
								},
								RMl1e1nPM: {
									"data-framer-name": "Tablet",
								},
								yPIBc3G1h: {
									"data-framer-name": "Variant 5",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-ymfj4u"}
							data-framer-name={"[Sakib]"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"JKNFp8PUu"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23))",
								"--framer-paragraph-spacing": "0px",
								opacity: 1,
							}}
							variants={{
								yPIBc3G1h: {
									opacity: 0,
								},
							}}
							verticalAlignment={"center"}
							whileHover={animation}
							withExternalLayout={true}
							{...addPropertyOverrides2(
								{
									k_0ApqBeX: {
										children: (
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-9w7x32"}
													data-styles-preset={"dKg4d4Wgl"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23)))",
													}}
												>
													<Link
														href={{
															webPageId: "augiA20Il",
														}}
														nodeId={"JKNFp8PUu"}
														openInNewTab={false}
														smoothScroll={false}
													>
														<motion2.a
															className={"framer-styles-preset-1k29llr"}
															data-styles-preset={"xFu4glIlZ"}
														>
															{"[Ethan Caldwell]"}
														</motion2.a>
													</Link>
												</motion2.p>
											</React2.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-9w7x32"}
									data-styles-preset={"dKg4d4Wgl"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23)))",
									}}
								>
									<Link
										href={{
											webPageId: "augiA20Il",
										}}
										nodeId={"JKNFp8PUu"}
										openInNewTab={false}
										smoothScroll={false}
									>
										<motion2.a
											className={"framer-styles-preset-o4rhpw"}
											data-styles-preset={"ZQGYZcz0Q"}
										>
											{"[Ethan Caldwell]"}
										</motion2.a>
									</Link>
								</motion2.p>
							</React2.Fragment>
						</RichText>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "pbBTU27pw",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "Ffjc3kRKy",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "uoX5ej26O",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "pbBTU27pw",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "Ffjc3kRKy",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "uoX5ej26O",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "pbBTU27pw",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "Ffjc3kRKy",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "uoX5ej26O",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "pbBTU27pw",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "Ffjc3kRKy",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "uoX5ej26O",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "pbBTU27pw",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "Ffjc3kRKy",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "uoX5ej26O",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks) => (
								<ComponentViewportProvider2
									height={38}
									y={
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) + 0
									}
								>
									<motion2.div
										className={"framer-1x71wiy-container"}
										layoutDependency={layoutDependency}
										layoutId={"CTK8yE4oa-container"}
									>
										{_jsx2(stdin_default3, {
											CBX0MYr_6: "About",
											D29tSpr5W: "mailto:nayeemurrsakib@gmail.com",
											fnTPRPrm9: resolvedLinks[0],
											fxifn0tt_: "Thoughts",
											height: "100%",
											id: "CTK8yE4oa",
											layoutId: "CTK8yE4oa",
											PUl9fstAh: "Cases",
											PvLdBEHqU: "Contact",
											sJUZJ7R37: resolvedLinks[2],
											SuYvin8wV: resolvedLinks[1],
											variant: "KHtbqq85K",
											width: "100%",
											...addPropertyOverrides2(
												{
													aySkskEZU: {
														fnTPRPrm9: resolvedLinks[3],
														sJUZJ7R37: resolvedLinks[5],
														SuYvin8wV: resolvedLinks[4],
													},
													k_0ApqBeX: {
														fnTPRPrm9: resolvedLinks[9],
														sJUZJ7R37: resolvedLinks[11],
														SuYvin8wV: resolvedLinks[10],
														variant: "d1YAUe7y8",
													},
													RMl1e1nPM: {
														fnTPRPrm9: resolvedLinks[6],
														sJUZJ7R37: resolvedLinks[8],
														SuYvin8wV: resolvedLinks[7],
													},
													yPIBc3G1h: {
														fnTPRPrm9: resolvedLinks[12],
														sJUZJ7R37: resolvedLinks[14],
														SuYvin8wV: resolvedLinks[13],
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</motion2.div>
								</ComponentViewportProvider2>
							)}
						</ResolveLinks>
					</motion2.nav>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-p9S3Q.framer-6eeus9, .framer-p9S3Q .framer-6eeus9 { display: block; }",
	".framer-p9S3Q.framer-18hy7lq { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 574px; height: min-content; justify-content: center; max-width: 800px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-p9S3Q .framer-ymfj4u { --framer-custom-cursors: pointer; flex: none; height: 38px; position: relative; white-space: pre; width: auto; }",
	".framer-p9S3Q .framer-1x71wiy-container { flex: none; height: auto; position: relative; width: auto; z-index: 10; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-p9S3Q.framer-18hy7lq { gap: 0px; } .framer-p9S3Q.framer-18hy7lq > * { margin: 0px; margin-left: calc(574px / 2); margin-right: calc(574px / 2); } .framer-p9S3Q.framer-18hy7lq > :first-child { margin-left: 0px; } .framer-p9S3Q.framer-18hy7lq > :last-child { margin-right: 0px; } }",
	".framer-p9S3Q.framer-v-1mwlzrf.framer-18hy7lq { gap: 462px; width: 690px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-p9S3Q.framer-v-1mwlzrf.framer-18hy7lq { gap: 0px; } .framer-p9S3Q.framer-v-1mwlzrf.framer-18hy7lq > * { margin: 0px; margin-left: calc(462px / 2); margin-right: calc(462px / 2); } .framer-p9S3Q.framer-v-1mwlzrf.framer-18hy7lq > :first-child { margin-left: 0px; } .framer-p9S3Q.framer-v-1mwlzrf.framer-18hy7lq > :last-child { margin-right: 0px; } }",
	".framer-p9S3Q.framer-v-z7s0vp.framer-18hy7lq { gap: unset; justify-content: space-between; max-width: unset; width: 324px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-p9S3Q.framer-v-z7s0vp.framer-18hy7lq { gap: 0px; } .framer-p9S3Q.framer-v-z7s0vp.framer-18hy7lq > *, .framer-p9S3Q.framer-v-z7s0vp.framer-18hy7lq > :first-child, .framer-p9S3Q.framer-v-z7s0vp.framer-18hy7lq > :last-child { margin: 0px; } }",
	".framer-p9S3Q.framer-v-1wuo9mc.framer-18hy7lq { gap: unset; justify-content: space-between; width: 800px; }",
	".framer-p9S3Q.framer-v-1wuo9mc .framer-ymfj4u { order: 0; }",
	".framer-p9S3Q.framer-v-1wuo9mc .framer-1x71wiy-container { order: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-p9S3Q.framer-v-1wuo9mc.framer-18hy7lq { gap: 0px; } .framer-p9S3Q.framer-v-1wuo9mc.framer-18hy7lq > *, .framer-p9S3Q.framer-v-1wuo9mc.framer-18hy7lq > :first-child, .framer-p9S3Q.framer-v-1wuo9mc.framer-18hy7lq > :last-child { margin: 0px; } }",
	...css,
	...css3,
	...css2,
];
var FramertCo4ObWfx = withCSS2(Component2, css5, "framer-p9S3Q");
var stdin_default4 = FramertCo4ObWfx;
FramertCo4ObWfx.displayName = "Navigation/Nav Bar";
FramertCo4ObWfx.defaultProps = {
	height: 38,
	width: 800,
};
addPropertyControls2(FramertCo4ObWfx, {
	variant: {
		options: ["Uq_535luA", "aySkskEZU", "RMl1e1nPM", "k_0ApqBeX", "yPIBc3G1h"],
		optionTitles: ["Desktop", "Desktop Small", "Tablet", "Phone", "Variant 5"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramertCo4ObWfx,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NavigationFullMenuFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/nav-bar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "k_0ApqBeX",
	md: "RMl1e1nPM",
	xl: "Uq_535luA",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var nav_bar_default = ComponentWithRoot;
export { nav_bar_default as default };
