// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

import { className, css, fonts } from "../chunks/chunk-SJ4Y2L4N.js";
import { routes } from "../chunks/chunk-IVPZFA75.js";

// virtual:navigation/nav-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5Jdl3KJzJ6cFJwVWCWbZ/WfHAbVYzv4xM37n1GnZ6/MpNfnZQe5.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-Y9KZ9";
var variantClassNames = {
	wEBwEn8Ty: "framer-v-j4xthy",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, title, width, ...props }) => {
	var _ref;
	return {
		...props,
		qg9thEk2O:
			(_ref = title !== null && title !== void 0 ? title : props.qg9thEk2O) !==
				null && _ref !== void 0
				? _ref
				: "About",
		sDHQdK2Y_: link !== null && link !== void 0 ? link : props.sDHQdK2Y_,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		qg9thEk2O,
		sDHQdK2Y_,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "wEBwEn8Ty",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={sDHQdK2Y_} nodeId={"wEBwEn8Ty"}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-j4xthy", className2, classNames)} framer-1mhd30o`}
							data-border={true}
							data-framer-name={"Nav Item"}
							layoutDependency={layoutDependency}
							layoutId={"wEBwEn8Ty"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-403f5250-c23f-4327-bcf3-4fb3df82b8c0, rgb(226, 225, 217))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backdropFilter: "blur(5px)",
								backgroundColor:
									"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
								borderBottomLeftRadius: 22,
								borderBottomRightRadius: 22,
								borderTopLeftRadius: 22,
								borderTopRightRadius: 22,
								WebkitBackdropFilter: "blur(5px)",
								...style,
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-19p78q8"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"DoyoBHXFJ"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={qg9thEk2O}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-9w7x32"}
										data-styles-preset={"dKg4d4Wgl"}
									>
										{"About"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Y9KZ9.framer-1mhd30o, .framer-Y9KZ9 .framer-1mhd30o { display: block; }",
	".framer-Y9KZ9.framer-j4xthy { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 10px 32px 10px 32px; position: relative; text-decoration: none; width: min-content; }",
	".framer-Y9KZ9 .framer-19p78q8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Y9KZ9.framer-j4xthy { gap: 0px; } .framer-Y9KZ9.framer-j4xthy > * { margin: 0px; margin-bottom: calc(6px / 2); margin-top: calc(6px / 2); } .framer-Y9KZ9.framer-j4xthy > :first-child { margin-top: 0px; } .framer-Y9KZ9.framer-j4xthy > :last-child { margin-bottom: 0px; } }",
	...css,
	'.framer-Y9KZ9[data-border="true"]::after, .framer-Y9KZ9 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerMpNfnZQe5 = withCSS(Component, css2, "framer-Y9KZ9");
var stdin_default = FramerMpNfnZQe5;
FramerMpNfnZQe5.displayName = "Navigation/Nav item";
FramerMpNfnZQe5.defaultProps = {
	height: 42,
	width: 103,
};
addPropertyControls(FramerMpNfnZQe5, {
	qg9thEk2O: {
		defaultValue: "About",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	sDHQdK2Y_: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerMpNfnZQe5,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/nav-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var nav_item_default = ComponentWithRoot;
export { nav_item_default as default };
