// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { routes } from "./chunks/chunk-IVPZFA75.js";

// virtual:intro
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/b6YoECf1KnT3Qx3sPWlI/NV7OKK3F226vDjnnIm7R/a6GGITUrK.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Floating,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOverlayState,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
var RichTextWithFX = withFX(RichText);
var enabledGestures = {
	D2HaBwD6t: {
		hover: true,
	},
};
var cycleOrder = ["D2HaBwD6t", "Fuqxs0rDs"];
var serializationHash = "framer-g9kyu";
var variantClassNames = {
	D2HaBwD6t: "framer-v-dnk51i",
	Fuqxs0rDs: "framer-v-xy0jdz",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 600,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 23,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "D2HaBwD6t",
	"Variant 2": "Fuqxs0rDs",
};
var getProps = ({ height, id, image, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		kfRbSzKC9:
			(_ref = image !== null && image !== void 0 ? image : props.kfRbSzKC9) !==
				null && _ref !== void 0
				? _ref
				: {
						alt: "",
						src: "https://framerusercontent.com/images/Mt389wY95stsCDJPQVHlrNWP0I.png?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/Mt389wY95stsCDJPQVHlrNWP0I.png 408w",
					},
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "D2HaBwD6t",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, kfRbSzKC9, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "D2HaBwD6t",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterupml6a = ({ overlay, loadMore }) =>
		activeVariantCallback(async (...args) => {
			setGestureState({
				isHovered: true,
			});
			overlay.show();
		});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "Fuqxs0rDs") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (gestureVariant === "D2HaBwD6t-hover") return true;
		return false;
	};
	const ref2 = React.useRef(null);
	const isDisplayed2 = () => {
		if (baseVariant === "Fuqxs0rDs") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Overlay blockDocumentScrolling={false} enabled={isDisplayed1()}>
					{(overlay) => (
						<_Fragment>
							<Transition value={transition1}>
								<motion.div
									{...restProps}
									{...gestureHandlers}
									className={cx(
										serializationHash,
										...sharedStyleClassNames,
										"framer-dnk51i",
										className,
										classNames,
									)}
									data-framer-name={"Variant 1"}
									data-highlight={true}
									id={`${layoutId}-dnk51i`}
									layoutDependency={layoutDependency}
									layoutId={"D2HaBwD6t"}
									onMouseEnter={onMouseEnterupml6a({
										overlay,
									})}
									ref={ref !== null && ref !== void 0 ? ref : ref1}
									style={{
										backgroundColor: "rgba(0, 0, 0, 0)",
										borderBottomLeftRadius: 0,
										borderBottomRightRadius: 0,
										borderTopLeftRadius: 0,
										borderTopRightRadius: 0,
										...style,
									}}
									variants={{
										Fuqxs0rDs: {
											backgroundColor:
												"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
											borderBottomLeftRadius: 90,
											borderBottomRightRadius: 90,
											borderTopLeftRadius: 90,
											borderTopRightRadius: 90,
										},
									}}
									{...addPropertyOverrides(
										{
											"D2HaBwD6t-hover": {
												"data-framer-name": void 0,
											},
											Fuqxs0rDs: {
												"data-framer-name": "Variant 2",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-1hocpxb"}
										layoutDependency={layoutDependency}
										layoutId={"mgTHeKOSd"}
										style={{
											backgroundColor:
												"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
											borderBottomLeftRadius: 90,
											borderBottomRightRadius: 90,
											borderTopLeftRadius: 90,
											borderTopRightRadius: 90,
										}}
									>
										<Image
											background={{
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														0 +
														0 -
														104,
												),
												sizes: "60px",
												...toResponsiveImage(kfRbSzKC9),
											}}
											className={"framer-t1ox9q"}
											data-framer-name={"Rectangle"}
											layoutDependency={layoutDependency}
											layoutId={"IIWarOa3g"}
											style={{
												borderBottomLeftRadius: 90,
												borderBottomRightRadius: 90,
												borderTopLeftRadius: 90,
												borderTopRightRadius: 90,
												scale: 1,
											}}
											variants={{
												"D2HaBwD6t-hover": {
													scale: 0.8,
												},
											}}
											{...addPropertyOverrides(
												{
													"D2HaBwD6t-hover": {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																((componentViewport === null ||
																componentViewport === void 0
																	? void 0
																	: componentViewport.y) || 0) +
																	0 +
																	0 -
																	97,
															),
															sizes: "74px",
															...toResponsiveImage(kfRbSzKC9),
														},
													},
													Fuqxs0rDs: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																((componentViewport === null ||
																componentViewport === void 0
																	? void 0
																	: componentViewport.y) || 0) +
																	0 +
																	((((componentViewport === null ||
																	componentViewport === void 0
																		? void 0
																		: componentViewport.height) || 141) -
																		0 -
																		141) /
																		2 +
																		0 +
																		0) +
																	141 -
																	116,
															),
															sizes: "52px",
															...toResponsiveImage(kfRbSzKC9),
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										{isDisplayed() && (
											<RichTextWithFX
												__fromCanvasComponent={true}
												className={"framer-ag3fna"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"C_kEFLNrH"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
													opacity: 0,
												}}
												transformTemplate={transformTemplate1}
												variants={{
													"D2HaBwD6t-hover": {
														opacity: 1,
													},
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														"D2HaBwD6t-hover": {
															__framer__loop: animation,
															__framer__loopEffectEnabled: true,
															__framer__loopRepeatDelay: 0,
															__framer__loopRepeatType: "mirror",
															__framer__loopTransition: transition2,
															__perspectiveFX: false,
															__smartComponentFX: true,
															__targetOpacity: 1,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--framer-font-size": "32px",
														}}
													>
														{"\u{1F44B}"}
													</motion.p>
												</React.Fragment>
											</RichTextWithFX>
										)}
									</motion.div>
									{isDisplayed1() && (
										<AnimatePresence>
											{overlay.visible && (
												<Floating
													alignment={"center"}
													anchorRef={
														ref !== null && ref !== void 0 ? ref : ref1
													}
													className={cx(
														serializationHash,
														classNames,
														...sharedStyleClassNames,
													)}
													collisionDetection={true}
													collisionDetectionPadding={20}
													data-framer-portal-id={`${layoutId}-dnk51i`}
													offsetX={10}
													offsetY={0}
													onDismiss={overlay.hide}
													placement={"right"}
													portalSelector={"#overlay"}
													safeArea={true}
													zIndex={2}
													{...addPropertyOverrides(
														{
															"D2HaBwD6t-hover": {
																alignment: "start",
																offsetX: 18,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<motion.div
														className={"framer-i1958n"}
														layoutDependency={layoutDependency}
														layoutId={"K8AQiaPYt"}
														ref={ref2}
														role={"dialog"}
														style={{
															backgroundColor: "rgb(255, 255, 255)",
															borderBottomLeftRadius: 10,
															borderBottomRightRadius: 10,
															borderTopLeftRadius: 10,
															borderTopRightRadius: 10,
														}}
														variants={{
															"D2HaBwD6t-hover": {
																backgroundColor: "rgba(0, 0, 0, 0)",
															},
														}}
													>
														{isDisplayed1() && (
															<motion.div
																className={"framer-ffs2ag"}
																layoutDependency={layoutDependency}
																layoutId={"Tqvv0mA05"}
																style={{
																	backdropFilter: "blur(0px)",
																	backgroundColor: "rgba(0, 0, 0, 0)",
																	borderBottomLeftRadius: 8,
																	borderBottomRightRadius: 8,
																	borderTopLeftRadius: 8,
																	WebkitBackdropFilter: "blur(0px)",
																}}
																variants={{
																	"D2HaBwD6t-hover": {
																		backdropFilter: "blur(5px)",
																		backgroundColor:
																			"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
																		WebkitBackdropFilter: "blur(5px)",
																	},
																}}
															>
																<RichText
																	__fromCanvasComponent={true}
																	className={"framer-112oiqj"}
																	fonts={["GF;Syne-700"]}
																	layoutDependency={layoutDependency}
																	layoutId={"DDT4qXpuD"}
																	style={{
																		"--extracted-1eung3n":
																			"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
																		"--framer-link-text-color":
																			"rgb(0, 153, 255)",
																		"--framer-link-text-decoration":
																			"underline",
																	}}
																	verticalAlignment={"top"}
																	withExternalLayout={true}
																>
																	<React.Fragment>
																		<motion.h4
																			style={{
																				"--font-selector": "R0Y7U3luZS03MDA=",
																				"--framer-font-family":
																					'"Syne", "Syne Placeholder", sans-serif',
																				"--framer-font-size": "12px",
																				"--framer-font-weight": "700",
																				"--framer-letter-spacing": "-0.04em",
																				"--framer-line-height": "140%",
																				"--framer-text-color":
																					"var(--extracted-1eung3n, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
																			}}
																		>
																			{"Welcome!"}
																			<motion.br />
																			{"Let's Explore"}
																		</motion.h4>
																	</React.Fragment>
																</RichText>
																{isDisplayed1() && (
																	<RichTextWithFX
																		__fromCanvasComponent={true}
																		className={"framer-1rspjv6"}
																		fonts={["GF;Syne-700"]}
																		layoutDependency={layoutDependency}
																		layoutId={"lLMpioxnC"}
																		style={{
																			"--extracted-1eung3n":
																				"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
																			"--framer-link-text-color":
																				"rgb(0, 153, 255)",
																			"--framer-link-text-decoration":
																				"underline",
																		}}
																		verticalAlignment={"top"}
																		withExternalLayout={true}
																		{...addPropertyOverrides(
																			{
																				"D2HaBwD6t-hover": {
																					__framer__loop: animation1,
																					__framer__loopEffectEnabled: true,
																					__framer__loopRepeatDelay: 0.1,
																					__framer__loopRepeatType: "mirror",
																					__framer__loopTransition: transition3,
																					__perspectiveFX: false,
																					__smartComponentFX: true,
																					__targetOpacity: 1,
																					children: (
																						<React.Fragment>
																							<motion.h4
																								style={{
																									"--font-selector":
																										"R0Y7U3luZS03MDA=",
																									"--framer-font-family":
																										'"Syne", "Syne Placeholder", sans-serif',
																									"--framer-font-size": "12px",
																									"--framer-font-weight": "700",
																									"--framer-letter-spacing":
																										"-0.04em",
																									"--framer-line-height":
																										"140%",
																									"--framer-text-color":
																										"var(--extracted-1eung3n, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
																								}}
																							>
																								{"."}
																							</motion.h4>
																						</React.Fragment>
																					),
																				},
																			},
																			baseVariant,
																			gestureVariant,
																		)}
																	>
																		<React.Fragment>
																			<motion.h4
																				style={{
																					"--font-selector": "R0Y7U3luZS03MDA=",
																					"--framer-font-family":
																						'"Syne", "Syne Placeholder", sans-serif',
																					"--framer-font-size": "12px",
																					"--framer-font-weight": "700",
																					"--framer-letter-spacing": "-0.04em",
																					"--framer-line-height": "140%",
																					"--framer-text-color":
																						"var(--extracted-1eung3n, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
																				}}
																			>
																				{"Hello!"}
																				<motion.br />
																				{"Let's Explore"}
																			</motion.h4>
																		</React.Fragment>
																	</RichTextWithFX>
																)}
																{isDisplayed1() && (
																	<RichTextWithFX
																		__fromCanvasComponent={true}
																		className={"framer-ww511"}
																		fonts={["GF;Syne-700"]}
																		layoutDependency={layoutDependency}
																		layoutId={"TsDIm6UAB"}
																		style={{
																			"--extracted-1eung3n":
																				"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
																			"--framer-link-text-color":
																				"rgb(0, 153, 255)",
																			"--framer-link-text-decoration":
																				"underline",
																		}}
																		verticalAlignment={"top"}
																		withExternalLayout={true}
																		{...addPropertyOverrides(
																			{
																				"D2HaBwD6t-hover": {
																					__framer__loop: animation1,
																					__framer__loopEffectEnabled: true,
																					__framer__loopRepeatDelay: 0.2,
																					__framer__loopRepeatType: "mirror",
																					__framer__loopTransition: transition3,
																					__perspectiveFX: false,
																					__smartComponentFX: true,
																					__targetOpacity: 1,
																				},
																			},
																			baseVariant,
																			gestureVariant,
																		)}
																	>
																		<React.Fragment>
																			<motion.h4
																				style={{
																					"--font-selector": "R0Y7U3luZS03MDA=",
																					"--framer-font-family":
																						'"Syne", "Syne Placeholder", sans-serif',
																					"--framer-font-size": "12px",
																					"--framer-font-weight": "700",
																					"--framer-letter-spacing": "-0.04em",
																					"--framer-line-height": "140%",
																					"--framer-text-color":
																						"var(--extracted-1eung3n, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
																				}}
																			>
																				{"."}
																			</motion.h4>
																		</React.Fragment>
																	</RichTextWithFX>
																)}
																{isDisplayed1() && (
																	<RichTextWithFX
																		__fromCanvasComponent={true}
																		className={"framer-13zo72u"}
																		fonts={["GF;Syne-700"]}
																		layoutDependency={layoutDependency}
																		layoutId={"zL1vFnAt4"}
																		style={{
																			"--extracted-1eung3n":
																				"var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32))",
																			"--framer-link-text-color":
																				"rgb(0, 153, 255)",
																			"--framer-link-text-decoration":
																				"underline",
																		}}
																		verticalAlignment={"top"}
																		withExternalLayout={true}
																		{...addPropertyOverrides(
																			{
																				"D2HaBwD6t-hover": {
																					__framer__loop: animation1,
																					__framer__loopEffectEnabled: true,
																					__framer__loopRepeatDelay: 0.1,
																					__framer__loopRepeatType: "mirror",
																					__framer__loopTransition: transition3,
																					__perspectiveFX: false,
																					__smartComponentFX: true,
																					__targetOpacity: 1,
																				},
																			},
																			baseVariant,
																			gestureVariant,
																		)}
																	>
																		<React.Fragment>
																			<motion.h4
																				style={{
																					"--font-selector": "R0Y7U3luZS03MDA=",
																					"--framer-font-family":
																						'"Syne", "Syne Placeholder", sans-serif',
																					"--framer-font-size": "12px",
																					"--framer-font-weight": "700",
																					"--framer-letter-spacing": "-0.04em",
																					"--framer-line-height": "140%",
																					"--framer-text-color":
																						"var(--extracted-1eung3n, var(--token-ab6739cc-dce6-4d8a-a1a9-bd5e94e6d75c, rgb(9, 64, 32)))",
																				}}
																			>
																				{"."}
																			</motion.h4>
																		</React.Fragment>
																	</RichTextWithFX>
																)}
																<motion.div
																	className={"framer-1cgccs8"}
																	layoutDependency={layoutDependency}
																	layoutId={"JiP1PR347"}
																	style={{
																		backgroundColor:
																			"var(--token-589ff8cc-db25-4c13-b2d2-416f607543ae, rgb(223, 252, 161))",
																		rotate: 225,
																	}}
																/>
															</motion.div>
														)}
													</motion.div>
												</Floating>
											)}
										</AnimatePresence>
									)}
									{isDisplayed2() && (
										<RichTextWithFX
											__framer__loop={animation}
											__framer__loopEffectEnabled={true}
											__framer__loopRepeatDelay={0}
											__framer__loopRepeatType={"mirror"}
											__framer__loopTransition={transition2}
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-f1wsxv"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"GfgGA1rNv"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											transformTemplate={transformTemplate1}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--framer-font-size": "32px",
													}}
												>
													{"\u{1F44B}"}
												</motion.p>
											</React.Fragment>
										</RichTextWithFX>
									)}
								</motion.div>
							</Transition>
						</_Fragment>
					)}
				</Overlay>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-g9kyu.framer-pe8hy1, .framer-g9kyu .framer-pe8hy1 { display: block; }",
	".framer-g9kyu.framer-dnk51i { cursor: pointer; height: 104px; overflow: hidden; position: relative; width: 60px; }",
	".framer-g9kyu .framer-1hocpxb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 0px; min-height: 104px; min-width: 60px; overflow: hidden; padding: 0px; position: absolute; top: 0px; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-g9kyu .framer-t1ox9q { bottom: 0px; flex: none; height: 104px; left: calc(50.00000000000002% - 60px / 2); position: absolute; width: 60px; z-index: 2; }",
	".framer-g9kyu .framer-ag3fna { bottom: -41px; flex: none; height: auto; left: 50%; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-g9kyu .framer-i1958n { height: 150px; overflow: hidden; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-g9kyu .framer-ffs2ag { align-content: flex-start; align-items: flex-start; bottom: -30px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: absolute; right: -283px; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-g9kyu .framer-112oiqj, .framer-g9kyu .framer-1rspjv6, .framer-g9kyu .framer-ww511, .framer-g9kyu .framer-13zo72u { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 2; }",
	".framer-g9kyu .framer-1cgccs8 { flex: none; height: 30px; left: -8px; overflow: hidden; position: absolute; top: calc(50.00000000000002% - 30px / 2); width: 30px; z-index: 0; }",
	".framer-g9kyu .framer-f1wsxv { flex: none; height: auto; left: 50%; position: absolute; top: 6px; white-space: pre; width: auto; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-g9kyu .framer-1hocpxb, .framer-g9kyu .framer-ffs2ag { gap: 0px; } .framer-g9kyu .framer-1hocpxb > *, .framer-g9kyu .framer-ffs2ag > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-g9kyu .framer-1hocpxb > :first-child, .framer-g9kyu .framer-ffs2ag > :first-child { margin-top: 0px; } .framer-g9kyu .framer-1hocpxb > :last-child, .framer-g9kyu .framer-ffs2ag > :last-child { margin-bottom: 0px; } }",
	".framer-g9kyu.framer-v-xy0jdz.framer-dnk51i { align-content: center; align-items: center; cursor: unset; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; width: min-content; }",
	".framer-g9kyu.framer-v-xy0jdz .framer-1hocpxb { height: 141px; left: unset; min-height: unset; min-width: unset; order: 1; padding: 10px 0px 10px 0px; position: relative; top: unset; width: 60px; }",
	".framer-g9kyu.framer-v-xy0jdz .framer-t1ox9q { bottom: -7px; height: 123px; left: calc(50.00000000000002% - 52px / 2); width: 52px; z-index: 3; }",
	".framer-g9kyu.framer-v-xy0jdz .framer-f1wsxv { order: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-g9kyu.framer-v-xy0jdz.framer-dnk51i { gap: 0px; } .framer-g9kyu.framer-v-xy0jdz.framer-dnk51i > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-g9kyu.framer-v-xy0jdz.framer-dnk51i > :first-child { margin-top: 0px; } .framer-g9kyu.framer-v-xy0jdz.framer-dnk51i > :last-child { margin-bottom: 0px; } }",
	".framer-g9kyu.framer-v-dnk51i.hover.framer-dnk51i { overflow: visible; }",
	".framer-g9kyu.framer-v-dnk51i.hover .framer-1hocpxb { min-width: unset; width: 100%; }",
	".framer-g9kyu.framer-v-dnk51i.hover .framer-t1ox9q { bottom: -31px; height: 128px; left: calc(50.00000000000002% - 74px / 2); width: 74px; }",
	".framer-g9kyu.framer-v-dnk51i.hover .framer-ag3fna { bottom: unset; top: 6px; }",
	".framer-g9kyu.framer-v-dnk51i.hover .framer-i1958n { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; width: min-content; }",
	".framer-g9kyu.framer-v-dnk51i.hover .framer-ffs2ag { align-content: flex-end; align-items: flex-end; bottom: unset; flex-direction: row; order: 0; overflow: visible; position: relative; right: unset; }",
	".framer-g9kyu.framer-v-dnk51i.hover .framer-1cgccs8 { height: 17px; left: -6px; top: calc(48.00000000000002% - 17px / 2); width: 19px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-g9kyu.framer-v-dnk51i.hover .framer-i1958n, .framer-g9kyu.framer-v-dnk51i.hover .framer-ffs2ag { gap: 0px; } .framer-g9kyu.framer-v-dnk51i.hover .framer-i1958n > *, .framer-g9kyu.framer-v-dnk51i.hover .framer-ffs2ag > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-g9kyu.framer-v-dnk51i.hover .framer-i1958n > :first-child, .framer-g9kyu.framer-v-dnk51i.hover .framer-ffs2ag > :first-child { margin-left: 0px; } .framer-g9kyu.framer-v-dnk51i.hover .framer-i1958n > :last-child, .framer-g9kyu.framer-v-dnk51i.hover .framer-ffs2ag > :last-child { margin-right: 0px; } }",
];
var Framera6GGITUrK = withCSS(Component, css, "framer-g9kyu");
var stdin_default = Framera6GGITUrK;
Framera6GGITUrK.displayName = "Intro";
Framera6GGITUrK.defaultProps = {
	height: 104,
	width: 60,
};
addPropertyControls(Framera6GGITUrK, {
	variant: {
		options: ["D2HaBwD6t", "Fuqxs0rDs"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	kfRbSzKC9: {
		__defaultAssetReference:
			"data:framer/asset-reference,Mt389wY95stsCDJPQVHlrNWP0I.png?originalFilename=Rectangle.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,Mt389wY95stsCDJPQVHlrNWP0I.png?originalFilename=Rectangle.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	Framera6GGITUrK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Syne",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_3fvj6hR47NCV5Z.woff2",
					weight: "700",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:intro
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Fuqxs0rDs",
	xl: "D2HaBwD6t",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IntroFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var intro_default = ComponentWithRoot;
export { intro_default as default };
