// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d16c07b25f9e9329 "UXfolio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * _01?: string // 01
 * _02?: string // 02
 * _03?: string // 03
}} Props

 */
import { routes } from "./chunks/chunk-IVPZFA75.js";

// virtual:process
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/m3lvQFoKpnkBfqHUl1TV/gooXIHQLMBsS5oSqFLAY/Ayrk32QKG.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/wj7WbbyAcVsfINPSvIjq/RatjhmNCVKdt47T1K0wv/htXtgXqYm.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;DM Sans-700",
	"GF;DM Sans-900",
	"GF;DM Sans-900italic",
	"GF;DM Sans-700italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwARZthS2f3ZGMZpg.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAC5thS2f3ZGMZpg.woff2",
				weight: "900",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat8gCm32RmYJpso5.woff2",
				weight: "900",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9uCm32RmYJpso5.woff2",
				weight: "700",
			},
		],
	},
];
var css = [
	'.framer-w3OQb .framer-styles-preset-1am8ijr:not(.rich-text-wrapper), .framer-w3OQb .framer-styles-preset-1am8ijr.rich-text-wrapper h6 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", sans-serif; --framer-font-family-bold-italic: "DM Sans", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, #171617); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 1200px) { .framer-w3OQb .framer-styles-preset-1am8ijr:not(.rich-text-wrapper), .framer-w3OQb .framer-styles-preset-1am8ijr.rich-text-wrapper h6 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", sans-serif; --framer-font-family-bold-italic: "DM Sans", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, #171617); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-w3OQb .framer-styles-preset-1am8ijr:not(.rich-text-wrapper), .framer-w3OQb .framer-styles-preset-1am8ijr.rich-text-wrapper h6 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", sans-serif; --framer-font-family-bold-italic: "DM Sans", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, #171617); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-w3OQb .framer-styles-preset-1am8ijr:not(.rich-text-wrapper), .framer-w3OQb .framer-styles-preset-1am8ijr.rich-text-wrapper h6 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", sans-serif; --framer-font-family-bold-italic: "DM Sans", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, #171617); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-w3OQb";

// /:https://framerusercontent.com/modules/ergd9NGWSKOrQ4OQjySQ/vUI2bIyarw0tGeYemB90/S8Dv9x0vl.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;DM Sans-regular",
	"GF;DM Sans-700",
	"GF;DM Sans-700italic",
	"GF;DM Sans-italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "DM Sans",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAopxhS2f3ZGMZpg.woff2",
				weight: "400",
			},
			{
				family: "DM Sans",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwARZthS2f3ZGMZpg.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9uCm32RmYJpso5.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat-JDW32RmYJpso5.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	`.framer-014Ht .framer-styles-preset-yv4o5b:not(.rich-text-wrapper), .framer-014Ht .framer-styles-preset-yv4o5b.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, #575757); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className2 = "framer-014Ht";

// /:https://framerusercontent.com/modules/m3lvQFoKpnkBfqHUl1TV/gooXIHQLMBsS5oSqFLAY/Ayrk32QKG.js
var serializationHash = "framer-GBxVb";
var variantClassNames = {
	CqXvNsUCb: "framer-v-erdveq",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ _01, _02, _03, height, id, title, width, ...props }) => {
	var _ref, _ref1, _ref2, _ref3;
	return {
		...props,
		c_ZyQroX0:
			(_ref = _01 !== null && _01 !== void 0 ? _01 : props.c_ZyQroX0) !==
				null && _ref !== void 0
				? _ref
				: "Conducted interviews with 15 frequent users to uncover frustrations and preferences.",
		DE2AYfEIy:
			(_ref1 = title !== null && title !== void 0 ? title : props.DE2AYfEIy) !==
				null && _ref1 !== void 0
				? _ref1
				: "[01] User Research",
		IBh2LtJVx:
			(_ref2 = _03 !== null && _03 !== void 0 ? _03 : props.IBh2LtJVx) !==
				null && _ref2 !== void 0
				? _ref2
				: "Benchmarked against competitors to identify best practices for checkout flows.",
		sApNeeffE:
			(_ref3 = _02 !== null && _02 !== void 0 ? _02 : props.sApNeeffE) !==
				null && _ref3 !== void 0
				? _ref3
				: "Analyzed behavioral data to identify bottlenecks in the current flow.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		DE2AYfEIy,
		c_ZyQroX0,
		sApNeeffE,
		IBh2LtJVx,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "CqXvNsUCb",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-erdveq",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"CqXvNsUCb"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-403f5250-c23f-4327-bcf3-4fb3df82b8c0, rgb(226, 225, 217))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgba(226, 225, 217, 0.2)",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-taf3ms"}
							data-framer-name={"[01] User Research"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"RfHsdvWAR"}
							style={{
								"--extracted-1w1cjl5":
									"var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={DE2AYfEIy}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h6
									className={"framer-styles-preset-1am8ijr"}
									data-styles-preset={"htXtgXqYm"}
									style={{
										"--framer-text-color":
											"var(--extracted-1w1cjl5, var(--token-612216c2-7343-4dea-ae48-08f52e0f59f6, rgb(23, 22, 23)))",
									}}
								>
									{"[01] User Research"}
								</motion.h6>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-1xf06ry"}
							data-border={true}
							data-framer-name={"01"}
							layoutDependency={layoutDependency}
							layoutId={"CDKvPEP8r"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgb(226, 225, 217)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-7afzu3"}
								data-framer-name={
									"Conducted interviews with 15 frequent users to uncover frustrations and preferences."
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"WcYrZXiE1"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={c_ZyQroX0}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-yv4o5b"}
										data-styles-preset={"S8Dv9x0vl"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87)))",
										}}
									>
										{
											"Conducted interviews with 15 frequent users to uncover frustrations and preferences."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-ynw5hi"}
							data-border={true}
							data-framer-name={"02"}
							layoutDependency={layoutDependency}
							layoutId={"l_jXVlWnQ"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgb(226, 225, 217)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-yjr6sg"}
								data-framer-name={
									"Analyzed behavioral data to identify bottlenecks in the current flow."
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"YmVKx2AoY"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={sApNeeffE}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-yv4o5b"}
										data-styles-preset={"S8Dv9x0vl"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87)))",
										}}
									>
										{
											"Analyzed behavioral data to identify bottlenecks in the current flow."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-1fbzox5"}
							data-framer-name={"03"}
							layoutDependency={layoutDependency}
							layoutId={"wXvdiKUa5"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-2wvw7a"}
								data-framer-name={
									"Benchmarked against competitors to identify best practices for checkout flows."
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"MK1keIS9g"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={IBh2LtJVx}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-yv4o5b"}
										data-styles-preset={"S8Dv9x0vl"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a62ea61d-ff7a-4157-8e11-935395736ce4, rgb(87, 87, 87)))",
										}}
									>
										{
											"Benchmarked against competitors to identify best practices for checkout flows."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-GBxVb.framer-1bmjni3, .framer-GBxVb .framer-1bmjni3 { display: block; }",
	".framer-GBxVb.framer-erdveq { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px; position: relative; width: min-content; }",
	".framer-GBxVb .framer-taf3ms { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 352px; word-break: break-word; word-wrap: break-word; }",
	".framer-GBxVb .framer-1xf06ry, .framer-GBxVb .framer-ynw5hi { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 8px 0px; position: relative; width: auto; }",
	".framer-GBxVb .framer-7afzu3, .framer-GBxVb .framer-yjr6sg, .framer-GBxVb .framer-2wvw7a { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-GBxVb .framer-1fbzox5 { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-GBxVb.framer-erdveq, .framer-GBxVb .framer-1xf06ry, .framer-GBxVb .framer-ynw5hi, .framer-GBxVb .framer-1fbzox5 { gap: 0px; } .framer-GBxVb.framer-erdveq > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-GBxVb.framer-erdveq > :first-child { margin-top: 0px; } .framer-GBxVb.framer-erdveq > :last-child { margin-bottom: 0px; } .framer-GBxVb .framer-1xf06ry > *, .framer-GBxVb .framer-ynw5hi > *, .framer-GBxVb .framer-1fbzox5 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-GBxVb .framer-1xf06ry > :first-child, .framer-GBxVb .framer-ynw5hi > :first-child, .framer-GBxVb .framer-1fbzox5 > :first-child { margin-left: 0px; } .framer-GBxVb .framer-1xf06ry > :last-child, .framer-GBxVb .framer-ynw5hi > :last-child, .framer-GBxVb .framer-1fbzox5 > :last-child { margin-right: 0px; } }",
	...css,
	...css2,
	'.framer-GBxVb[data-border="true"]::after, .framer-GBxVb [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerAyrk32QKG = withCSS(Component, css3, "framer-GBxVb");
var stdin_default = FramerAyrk32QKG;
FramerAyrk32QKG.displayName = "Process";
FramerAyrk32QKG.defaultProps = {
	height: 237,
	width: 392,
};
addPropertyControls(FramerAyrk32QKG, {
	DE2AYfEIy: {
		defaultValue: "[01] User Research",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	c_ZyQroX0: {
		defaultValue:
			"Conducted interviews with 15 frequent users to uncover frustrations and preferences.",
		displayTextArea: false,
		title: "01",
		type: ControlType.String,
	},
	sApNeeffE: {
		defaultValue:
			"Analyzed behavioral data to identify bottlenecks in the current flow.",
		displayTextArea: false,
		title: "02",
		type: ControlType.String,
	},
	IBh2LtJVx: {
		defaultValue:
			"Benchmarked against competitors to identify best practices for checkout flows.",
		displayTextArea: false,
		title: "03",
		type: ControlType.String,
	},
});
addFonts(
	FramerAyrk32QKG,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:process
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProcessFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d16c07b25f9e93299db8062dcbde5bc164a1f3444737edab711d94b54497989d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var process_default = ComponentWithRoot;
export { process_default as default };
