'use client'

import { useState } from 'react'
import { HeroTextVariation } from '@/components/hero/HeroTextVariations'

const textVariations = [
  // Current - Subheading First
  {
    id: 'current',
    name: 'Current (Subheading First)',
    description: 'CS Grad on top, large serif name, Inter tagline',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-2xl md:text-3xl lg:text-4xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Editorial Old Variations
  {
    id: 'editorial-bold',
    name: 'Editorial Bold',
    description: 'CS Grad on top, bold Editorial Old name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-bold',
    subheadingSize: 'text-3xl md:text-4xl lg:text-5xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-2xl md:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'editorial-italic',
    name: 'Editorial Italic',
    description: 'CS Grad on top, italic Editorial Old name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light italic',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-2xl md:text-3xl lg:text-4xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'editorial-large-subheading',
    name: 'Editorial - Large Subheading',
    description: 'Large CS Grad, Editorial Old name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-4xl md:text-5xl lg:text-6xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Inter Variations
  {
    id: 'inter-light',
    name: 'Inter Light',
    description: 'CS Grad on top, all Inter light',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Inter',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-2xl md:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'inter-bold',
    name: 'Inter Bold',
    description: 'CS Grad on top, bold Inter name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Inter',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'inter-medium',
    name: 'Inter Medium',
    description: 'CS Grad on top, medium Inter throughout',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Inter',
    nameStyle: 'font-medium',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'inter-italic',
    name: 'Inter Italic',
    description: 'CS Grad on top, italic Inter name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Inter',
    nameStyle: 'font-light italic',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'editorial-italic',
    name: 'Editorial Italic',
    description: 'CS Grad on top, italic Editorial Old name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light italic',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-2xl md:text-3xl lg:text-4xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'fraunces-italic',
    name: 'Fraunces Italic',
    description: 'CS Grad on top, italic Fraunces name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light italic',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'subheading-italic',
    name: 'Italic CS Grad',
    description: 'Italic CS Grad, Editorial Old name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    subheadingItalic: true,
    taglineSize: 'text-2xl md:text-3xl lg:text-4xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'tagline-italic',
    name: 'Italic Tagline',
    description: 'CS Grad on top, italic tagline',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-2xl md:text-3xl lg:text-4xl',
    taglineFont: 'Inter',
    taglineItalic: true,
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'all-italic',
    name: 'All Italic',
    description: 'CS Grad, name, and tagline all italic',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light italic',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    subheadingItalic: true,
    taglineSize: 'text-2xl md:text-3xl lg:text-4xl',
    taglineFont: 'Inter',
    taglineItalic: true,
    order: 'subheading-name-tagline' as const,
  },
  // Feature Font Variations
  {
    id: 'feature-name',
    name: 'Feature Name',
    description: 'CS Grad on top, Feature font name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Feature',
    nameStyle: 'font-normal',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'feature-all',
    name: 'Feature Throughout',
    description: 'CS Grad on top, Feature font throughout',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Feature',
    nameStyle: 'font-normal',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Feature',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Feature',
    order: 'subheading-name-tagline' as const,
  },
  // National 2 Variations
  {
    id: 'national-name',
    name: 'National 2 Name',
    description: 'CS Grad on top, National 2 name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'National 2',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'national-all',
    name: 'National 2 Throughout',
    description: 'CS Grad on top, National 2 throughout',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'National 2',
    nameStyle: 'font-bold',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'National 2',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'National 2',
    order: 'subheading-name-tagline' as const,
  },
  // Fraunces Variations
  {
    id: 'fraunces-name',
    name: 'Fraunces Name',
    description: 'CS Grad on top, Fraunces serif name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'fraunces-all',
    name: 'Fraunces Throughout',
    description: 'CS Grad on top, Fraunces serif throughout',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Fraunces',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Fraunces',
    order: 'subheading-name-tagline' as const,
  },
  // DM Sans Variations
  {
    id: 'dm-sans-name',
    name: 'DM Sans Name',
    description: 'CS Grad on top, DM Sans name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'DM Sans',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'dm-sans-all',
    name: 'DM Sans Throughout',
    description: 'CS Grad on top, DM Sans throughout',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'DM Sans',
    nameStyle: 'font-bold',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'DM Sans',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'DM Sans',
    order: 'subheading-name-tagline' as const,
  },
  // Syne Variations
  {
    id: 'syne-name',
    name: 'Syne Name',
    description: 'CS Grad on top, Syne bold name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Syne',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'syne-all',
    name: 'Syne Throughout',
    description: 'CS Grad on top, Syne throughout',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Syne',
    nameStyle: 'font-bold',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Syne',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Syne',
    order: 'subheading-name-tagline' as const,
  },
  // Size Variations
  {
    id: 'extra-large-name',
    name: 'Extra Large Name',
    description: 'CS Grad on top, very large name',
    nameSize: 'text-[7rem] md:text-[9rem] lg:text-[12rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-lg md:text-xl lg:text-2xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'compact-all',
    name: 'Compact All',
    description: 'CS Grad on top, smaller sizing throughout',
    nameSize: 'text-[3.5rem] md:text-[5rem] lg:text-[7rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-base md:text-lg lg:text-xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'large-subheading',
    name: 'Large Subheading',
    description: 'Large CS Grad, Editorial Old name',
    nameSize: 'text-[3.5rem] md:text-[5rem] lg:text-[7rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    subheadingFont: 'Editorial Old',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'balanced-medium',
    name: 'Balanced Medium',
    description: 'CS Grad on top, balanced medium sizes',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'small-name-large-subheading',
    name: 'Small Name, Large CS Grad',
    description: 'Large CS Grad, smaller name',
    nameSize: 'text-[3rem] md:text-[4rem] lg:text-[6rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[4rem] md:text-[5rem] lg:text-[7rem]',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Mixed Font Combinations
  {
    id: 'editorial-inter-feature',
    name: 'Editorial-Inter-Feature',
    description: 'CS Grad Inter, Editorial name, Feature tagline',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Feature',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'national-feature-inter',
    name: 'National-Feature-Inter',
    description: 'CS Grad Feature, National name, Inter tagline',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'National 2',
    nameStyle: 'font-bold',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Feature',
    taglineSize: 'text-xl md:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'inter-editorial-feature',
    name: 'Inter-Editorial-Feature',
    description: 'CS Grad Inter, Editorial name, Feature tagline',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Feature',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'fraunces-inter-feature',
    name: 'Fraunces-Inter-Feature',
    description: 'CS Grad Inter, Fraunces name, Feature tagline',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Feature',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'syne-inter-editorial',
    name: 'Syne-Inter-Editorial',
    description: 'CS Grad Inter, Syne name, Editorial tagline',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Syne',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Editorial Old',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'editorial-bold-inter',
    name: 'Editorial Bold-Inter',
    description: 'CS Grad Inter, bold Editorial name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-bold',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'inter-medium-editorial',
    name: 'Inter Medium-Editorial',
    description: 'CS Grad Inter medium, Editorial name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-medium',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Editorial Old',
    order: 'subheading-name-tagline' as const,
  },
  // Extra Large Variations
  {
    id: 'extra-large-editorial',
    name: 'Extra Large Editorial',
    description: 'CS Grad on top, massive Editorial name',
    nameSize: 'text-[8rem] md:text-[10rem] lg:text-[13rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'extra-large-inter',
    name: 'Extra Large Inter',
    description: 'CS Grad on top, massive Inter name',
    nameSize: 'text-[8rem] md:text-[10rem] lg:text-[13rem]',
    nameFont: 'Inter',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'extra-large-syne',
    name: 'Extra Large Syne',
    description: 'CS Grad on top, massive Syne name',
    nameSize: 'text-[8rem] md:text-[10rem] lg:text-[13rem]',
    nameFont: 'Syne',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Small Name, Large Subheading Variations
  {
    id: 'small-name-huge-subheading',
    name: 'Small Name, Huge CS Grad',
    description: 'Massive CS Grad, smaller name',
    nameSize: 'text-[2.5rem] md:text-[3.5rem] lg:text-[5rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'small-name-huge-subheading-editorial',
    name: 'Small Name, Huge CS Grad Editorial',
    description: 'Massive CS Grad Editorial, smaller name',
    nameSize: 'text-[2.5rem] md:text-[3.5rem] lg:text-[5rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    subheadingFont: 'Editorial Old',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Balanced Medium Variations
  {
    id: 'balanced-medium-editorial',
    name: 'Balanced Medium Editorial',
    description: 'CS Grad on top, balanced medium sizes',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'balanced-medium-inter',
    name: 'Balanced Medium Inter',
    description: 'CS Grad on top, balanced medium Inter',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Inter',
    nameStyle: 'font-medium',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'balanced-medium-fraunces',
    name: 'Balanced Medium Fraunces',
    description: 'CS Grad on top, balanced medium Fraunces',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Compact Variations
  {
    id: 'compact-editorial',
    name: 'Compact Editorial',
    description: 'CS Grad on top, compact Editorial',
    nameSize: 'text-[3rem] md:text-[4.5rem] lg:text-[6rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-base md:text-lg lg:text-xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-base md:text-lg',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'compact-inter',
    name: 'Compact Inter',
    description: 'CS Grad on top, compact Inter',
    nameSize: 'text-[3rem] md:text-[4.5rem] lg:text-[6rem]',
    nameFont: 'Inter',
    nameStyle: 'font-medium',
    subheadingSize: 'text-base md:text-lg lg:text-xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-base md:text-lg',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'compact-feature',
    name: 'Compact Feature',
    description: 'CS Grad on top, compact Feature',
    nameSize: 'text-[3rem] md:text-[4.5rem] lg:text-[6rem]',
    nameFont: 'Feature',
    nameStyle: 'font-normal',
    subheadingSize: 'text-base md:text-lg lg:text-xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-base md:text-lg',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Large Subheading Variations
  {
    id: 'large-subheading-editorial',
    name: 'Large CS Grad Editorial',
    description: 'Large CS Grad Editorial, Editorial name',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    subheadingFont: 'Editorial Old',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'large-subheading-inter',
    name: 'Large CS Grad Inter',
    description: 'Large CS Grad Inter, Editorial name',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'large-subheading-feature',
    name: 'Large CS Grad Feature',
    description: 'Large CS Grad Feature, Editorial name',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    subheadingFont: 'Feature',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Font Weight Variations
  {
    id: 'editorial-light-subheading-bold',
    name: 'Editorial Light, Bold CS Grad',
    description: 'Light Editorial name, bold CS Grad',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'inter-bold-subheading-light',
    name: 'Inter Bold, Light CS Grad',
    description: 'Bold Inter name, light CS Grad',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Inter',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'syne-bold-subheading-medium',
    name: 'Syne Bold, Medium CS Grad',
    description: 'Bold Syne name, medium CS Grad',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Syne',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // DM Sans Variations
  {
    id: 'dm-sans-bold-large',
    name: 'DM Sans Bold Large',
    description: 'CS Grad on top, large DM Sans bold',
    nameSize: 'text-[6rem] md:text-[8rem] lg:text-[10rem]',
    nameFont: 'DM Sans',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'dm-sans-medium-balanced',
    name: 'DM Sans Medium Balanced',
    description: 'CS Grad on top, balanced DM Sans',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'DM Sans',
    nameStyle: 'font-medium',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'dm-sans-all-medium',
    name: 'DM Sans All Medium',
    description: 'CS Grad DM Sans, DM Sans name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'DM Sans',
    nameStyle: 'font-medium',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'DM Sans',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'DM Sans',
    order: 'subheading-name-tagline' as const,
  },
  // Fraunces Variations
  {
    id: 'fraunces-light-large',
    name: 'Fraunces Light Large',
    description: 'CS Grad on top, large Fraunces light',
    nameSize: 'text-[6rem] md:text-[8rem] lg:text-[10rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'fraunces-medium-balanced',
    name: 'Fraunces Medium Balanced',
    description: 'CS Grad on top, balanced Fraunces',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Feature Variations
  {
    id: 'feature-large',
    name: 'Feature Large',
    description: 'CS Grad on top, large Feature',
    nameSize: 'text-[6rem] md:text-[8rem] lg:text-[10rem]',
    nameFont: 'Feature',
    nameStyle: 'font-normal',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'feature-medium-balanced',
    name: 'Feature Medium Balanced',
    description: 'CS Grad on top, balanced Feature',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'Feature',
    nameStyle: 'font-normal',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // National 2 Variations
  {
    id: 'national-bold-large',
    name: 'National 2 Bold Large',
    description: 'CS Grad on top, large National 2 bold',
    nameSize: 'text-[6rem] md:text-[8rem] lg:text-[10rem]',
    nameFont: 'National 2',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'national-medium-balanced',
    name: 'National 2 Medium Balanced',
    description: 'CS Grad on top, balanced National 2',
    nameSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    nameFont: 'National 2',
    nameStyle: 'font-bold',
    subheadingSize: 'text-xl md:text-2xl lg:text-3xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-lg md:text-xl lg:text-2xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Creative Font Combinations
  {
    id: 'editorial-subheading-fraunces-name',
    name: 'Editorial CS Grad, Fraunces Name',
    description: 'Editorial CS Grad, Fraunces name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Editorial Old',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'feature-subheading-editorial-name',
    name: 'Feature CS Grad, Editorial Name',
    description: 'Feature CS Grad, Editorial name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Feature',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'syne-subheading-editorial-name',
    name: 'Syne CS Grad, Editorial Name',
    description: 'Syne CS Grad, Editorial name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'Syne',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'dm-sans-subheading-fraunces-name',
    name: 'DM Sans CS Grad, Fraunces Name',
    description: 'DM Sans CS Grad, Fraunces name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Fraunces',
    nameStyle: 'font-light',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'DM Sans',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'national-subheading-feature-name',
    name: 'National CS Grad, Feature Name',
    description: 'National CS Grad, Feature name',
    nameSize: 'text-[5rem] md:text-[7rem] lg:text-[9rem]',
    nameFont: 'Feature',
    nameStyle: 'font-normal',
    subheadingSize: 'text-2xl md:text-3xl lg:text-4xl',
    subheadingFont: 'National 2',
    taglineSize: 'text-xl md:text-2xl lg:text-3xl',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  // Size Experimentation
  {
    id: 'tiny-name-large-subheading',
    name: 'Tiny Name, Large CS Grad',
    description: 'Very small name, large CS Grad',
    nameSize: 'text-[2rem] md:text-[3rem] lg:text-[4rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[4rem] md:text-[6rem] lg:text-[8rem]',
    subheadingFont: 'Inter',
    taglineSize: 'text-base md:text-lg',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'huge-name-small-subheading',
    name: 'Huge Name, Small CS Grad',
    description: 'Very large name, small CS Grad',
    nameSize: 'text-[9rem] md:text-[11rem] lg:text-[14rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-lg md:text-xl lg:text-2xl',
    subheadingFont: 'Inter',
    taglineSize: 'text-base md:text-lg',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
  {
    id: 'equal-size-all',
    name: 'Equal Size All',
    description: 'CS Grad, name, and tagline same size',
    nameSize: 'text-[3rem] md:text-[4rem] lg:text-[5rem]',
    nameFont: 'Editorial Old',
    nameStyle: 'font-light',
    subheadingSize: 'text-[3rem] md:text-[4rem] lg:text-[5rem]',
    subheadingFont: 'Inter',
    taglineSize: 'text-[3rem] md:text-[4rem] lg:text-[5rem]',
    taglineFont: 'Inter',
    order: 'subheading-name-tagline' as const,
  },
]

export default function HeroTextOptionsPage() {
  const [selectedVariation, setSelectedVariation] = useState('current')

  const selected = textVariations.find(v => v.id === selectedVariation) || textVariations[0]

  return (
    <main className="w-full min-h-screen transition-colors pt-24 pb-12">
      <div className="w-full px-4 md:px-8">
        {/* Header */}
        <div className="w-full max-w-7xl mx-auto mb-12">
          <h2 className="text-3xl font-light text-[#2A2A2A] dark:text-white mb-2 text-center" style={{ fontFamily: "Editorial Old" }}>
            Hero Text Variations ({textVariations.length} options)
          </h2>
          <p className="text-center text-gray-600 dark:text-gray-400 text-sm" style={{ fontFamily: "Inter" }}>
            Scroll to see all variations at full size
          </p>
        </div>

        {/* Full-Size Hero Previews */}
        <div className="w-full space-y-8">
          {textVariations.map((variation) => (
            <div
              key={variation.id}
              className={`w-full transition-all ${
                selectedVariation === variation.id
                  ? 'ring-4 ring-[#2A2A2A] dark:ring-white rounded-2xl'
                  : ''
              }`}
            >
              {/* Variation Label */}
              <div className="w-full max-w-[95%] md:max-w-[85%] lg:max-w-[75%] xl:max-w-[65%] 2xl:max-w-[60%] mx-auto mb-4">
                <div
                  onClick={() => setSelectedVariation(variation.id)}
                  className={`inline-block px-4 py-2 rounded-lg cursor-pointer transition-all ${
                    selectedVariation === variation.id
                      ? 'bg-[#2A2A2A] dark:bg-white text-white dark:text-[#2A2A2A]'
                      : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700'
                  }`}
                >
                  <div className="text-sm font-semibold" style={{ fontFamily: "Inter" }}>
                    {variation.name}
                  </div>
                  <div className="text-xs mt-1 opacity-75" style={{ fontFamily: "Inter" }}>
                    {variation.description}
                  </div>
                </div>
              </div>

              {/* Full Hero Preview */}
              <div className="w-full flex justify-center">
                <HeroTextVariation 
                  nameSize={variation.nameSize}
                  nameFont={variation.nameFont}
                  nameStyle={variation.nameStyle}
                  subheadingSize={variation.subheadingSize}
                  subheadingFont={variation.subheadingFont}
                  subheadingItalic={variation.subheadingItalic}
                  taglineSize={variation.taglineSize}
                  taglineFont={variation.taglineFont}
                  taglineItalic={variation.taglineItalic}
                  name={variation.name}
                  order={variation.order}
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  )
}
